// Categoría oficial naranja: "Acción. Cosas que se pueden realizar."
// Todo lo de aquí debe ser un verbo o una acción ejecutable.

export const action = {
  1: [
    "correr", "saltar", "nadar", "dormir", "comer", "beber", "llorar", "reír",
    "cantar", "bailar", "escribir", "leer", "dibujar", "pintar", "cocinar",
    "conducir", "volar", "caer", "empujar", "tirar", "abrazar", "besar",
    "saludar", "aplaudir", "señalar", "cavar", "cortar", "pegar", "romper",
    "lanzar", "atrapar", "patear", "golpear", "trepar", "esquiar", "patinar",
    "pescar", "remar", "barrer", "fregar", "planchar", "peinarse", "ducharse",
    "cepillarse los dientes", "vestirse", "atarse los cordones",
    "abrir una puerta", "subir una escalera", "sentarse", "levantarse",
    "estirarse", "andar", "gatear", "rodar", "esconderse", "buscar", "contar",
    "mirar", "escuchar", "oler", "soplar", "silbar", "empujar un columpio",
    "montar en bici", "regar las plantas", "lavarse las manos", "hacer fotos",
  ],
  2: [
    "bostezar", "estornudar", "roncar", "eructar", "suspirar", "sonrojarse",
    "guiñar", "parpadear", "fruncir el ceño", "poner los ojos en blanco",
    "sacar la lengua", "tararear", "susurrar", "cuchichear", "gritar",
    "tropezar", "resbalar", "desperezarse", "tambalearse", "cojear",
    "arrastrarse", "escabullirse", "espiar", "acechar", "perseguir", "huir",
    "esquivar", "agacharse", "encogerse", "estremecerse", "temblar", "sudar",
    "tiritar", "rascarse", "hacer equilibrio", "dar una voltereta",
    "hacer el pino", "saltar a la comba", "jugar al escondite", "columpiarse",
    "hacer pompas", "soplar las velas", "morder", "masticar", "sorber",
    "tragar", "escupir", "saborear", "acariciar", "pellizcar",
    "hacer cosquillas", "empujar un carrito", "llevar a caballito",
    "hacer la ola", "dar palmas", "chasquear los dedos", "taconear",
    "dar un portazo", "apagar la luz", "colgar el teléfono",
  ],
  3: [
    "amasar", "batir", "rallar", "pelar", "deshuesar", "flambear", "escurrir",
    "colar", "marinar", "desplumar", "aliñar", "hornear", "freír", "remover",
    "servir", "brindar", "soldar", "lijar", "atornillar", "desenroscar",
    "clavar", "enchufar", "taladrar", "empapelar", "alicatar",
    "pintar una pared", "montar un mueble", "cambiar una bombilla",
    "desatascar", "tender la ropa", "sacar la basura", "quitar el polvo",
    "hacer la cama", "poner la mesa", "hacer cola", "adelantar",
    "aparcar en batería", "frenar en seco", "dar marcha atrás",
    "poner una multa", "pinchar una rueda", "echar gasolina",
    "arrancar el coche", "hacer la maleta", "facturar el equipaje",
    "perder el vuelo", "pasar el control", "hacer autostop", "mudarse",
    "echar una siesta", "poner el despertador", "quedarse dormido",
    "madrugar", "trasnochar", "hacer la compra", "regatear",
    "pagar con tarjeta", "devolver el cambio", "dar propina",
    "envolver un regalo", "montar una tienda de campaña", "encender una hoguera",
    "hacer dedo", "pasar página", "cortar el césped",
  ],
  4: [
    "pujar", "subastar", "hipotecar", "invertir", "ahorrar", "cobrar",
    "facturar", "fichar en el trabajo", "delegar", "negociar", "mediar",
    "improvisar", "disimular", "procrastinar", "chantajear", "sobornar",
    "plagiar", "boicotear", "deducir", "memorizar", "traducir", "interpretar",
    "jubilarse", "dimitir", "ascender", "despedir", "contratar", "reclamar",
    "denunciar", "demandar", "testificar", "declarar", "absolver", "condenar",
    "indultar", "votar", "abstenerse", "censurar", "vetar", "legislar",
    "recaudar", "subvencionar", "patrocinar", "donar", "heredar", "legar",
    "adoptar", "divorciarse", "reconciliarse", "perdonar", "envidiar",
    "compadecer", "presumir", "exagerar", "malinterpretar", "titubear",
    "refunfuñar", "chismorrear", "gandulear", "escaquearse", "rumiar",
    "tantear", "hojear", "delatar", "amañar un partido", "fingir una lesión",
  ],
  5: [
    "abstraer", "inferir", "extrapolar", "generalizar", "sintetizar",
    "matizar", "relativizar", "cuestionar", "refutar", "argumentar",
    "debatir", "persuadir", "manipular", "adoctrinar", "moderar",
    "empatizar", "racionalizar", "reprimir", "sublimar", "idealizar",
    "resignarse", "perseverar", "claudicar", "reincidir", "recaer",
    "redimirse", "expiar", "renunciar", "sacrificar", "arriesgar",
    "apostar", "especular", "anticipar", "predecir", "intuir", "presentir",
    "dudar", "confiar", "desconfiar", "sospechar", "tirar la toalla",
    "meter la pata", "dar en el clavo", "hacer la vista gorda",
    "echar leña al fuego", "romper el hielo", "irse por las ramas",
    "buscar tres pies al gato", "dorar la píldora", "escurrir el bulto",
    "pasar la pelota", "tirar de la manta",
    "poner las cartas sobre la mesa", "morder el anzuelo",
    "dar gato por liebre", "tomar el pelo", "hacer oídos sordos",
    "dormirse en los laureles", "nadar y guardar la ropa",
    "predicar con el ejemplo",
  ],
};
