// Categoría "Todos juegan": ambos equipos compiten a la vez, así que las
// palabras deben ser visualmente ricas y de lectura rápida.
// N1 icónico · N2 específico · N3 escena · N4 abstracto anclable · N5 metáfora

export const all = {
  1: [
    "sol", "luna", "casa", "árbol", "coche", "perro", "gato", "pez", "flor",
    "estrella", "corazón", "nube", "montaña", "barco", "avión", "tren",
    "bicicleta", "pelota", "globo", "regalo", "tarta", "pizza", "helado",
    "plátano", "manzana", "zapato", "sombrero", "gafas", "paraguas", "llave",
    "martillo", "tijeras", "silla", "cama", "puerta", "ventana", "escalera",
    "reloj", "libro", "lápiz", "guitarra", "tambor", "robot", "fantasma",
    "calavera", "corona", "ancla", "cactus", "iglú", "faro", "castillo",
    "puente", "cohete", "dinosaurio", "mariposa", "abeja", "caracol",
    "serpiente", "tortuga", "cangrejo", "pingüino", "elefante", "jirafa",
    "león", "oso", "búho", "murciélago", "araña", "pulpo", "ballena",
    "tiburón", "cebra", "camello", "canguro", "rana", "huevo", "queso",
    "hamburguesa", "arcoíris", "diana", "semáforo", "vela", "escoba",
    "sombrilla", "columpio", "cometa", "pirata", "payaso",
  ],
  2: [
    "volcán", "pirámide", "esfinge", "obelisco", "catedral", "noria",
    "montaña rusa", "tiovivo", "trampolín", "tobogán", "hamaca",
    "tienda de campaña", "hoguera", "brújula", "telescopio", "microscopio",
    "periscopio", "submarino", "globo aerostático", "paracaídas", "ala delta",
    "helicóptero", "quitanieves", "excavadora", "grúa", "camión de bomberos",
    "ambulancia", "furgoneta", "caravana", "tractor", "patinete", "monociclo",
    "triciclo", "trineo", "canoa", "góndola", "salvavidas", "medusa", "morsa",
    "tucán", "flamenco", "camaleón", "erizo", "topo", "mapache", "jabalí",
    "castor", "perezoso", "armadillo", "suricata", "narval", "espantapájaros",
    "molino de viento", "laberinto", "acueducto", "muralla", "torre de control",
    "cabina telefónica", "buzón", "farola", "hidrante", "veleta", "pararrayos",
    "gramófono", "máquina de escribir", "acordeón", "xilófono", "arpa", "gaita",
    "saxofón", "bola de discoteca", "marioneta", "peonza", "caleidoscopio",
    "reloj de arena", "jaula", "caña de pescar", "carretilla", "regadera",
    "bumerán", "yunque", "catapulta", "ariete", "armadura", "escudo",
  ],
  3: [
    "atasco", "mudanza", "boda", "funeral", "huelga", "manifestación",
    "desfile", "carnaval", "mercadillo", "rebajas", "karaoke", "barbacoa",
    "picnic", "safari", "crucero", "naufragio", "rescate en helicóptero",
    "incendio forestal", "terremoto", "inundación", "avalancha",
    "erupción volcánica", "eclipse solar", "aterrizaje de emergencia",
    "atraco a un banco", "fuga de la cárcel", "juicio", "coronación",
    "podio olímpico", "penalti", "tarjeta roja", "foto finish", "maratón",
    "hora punta", "apagón", "tormenta de arena", "cola del supermercado",
    "control de seguridad", "cambio de rueda", "obras en la calle",
    "corte de pelo", "clase de yoga", "examen final", "primera cita",
    "cena romántica", "fiesta sorpresa", "visita al dentista",
    "caída de dominó", "guerra de almohadas", "guerra de bolas de nieve",
    "castillo de naipes", "pesca en el hielo", "paseo en globo",
    "persecución policial", "rueda de prensa", "alfombra roja",
    "sesión de fotos", "coro de villancicos", "vuelta al cole",
    "búsqueda del tesoro", "carrera de sacos", "tiro con arco",
    "salto de longitud", "relevo de testigo", "pistoletazo de salida",
    "vuelta de honor", "grada llena", "ola en el estadio",
  ],
  4: [
    "gravedad", "equilibrio", "simetría", "reflejo", "sombra", "eco",
    "vértigo", "insomnio", "resaca", "nostalgia", "envidia", "orgullo",
    "pánico escénico", "mala suerte", "casualidad", "superstición",
    "inflación", "jubilación", "herencia", "hipoteca", "propina", "multa",
    "subasta", "monopolio", "censura", "propaganda", "cuarentena",
    "caducidad", "garantía", "presupuesto", "inventario", "plagio",
    "soborno", "coartada", "ascenso", "despido", "deuda", "ahorro",
    "alergia", "calambre", "agujetas", "flato", "hipo", "mareo",
    "claustrofobia", "daltonismo", "amnesia", "telepatía", "hipnosis",
    "karma", "destino", "rutina", "aburrimiento", "impaciencia",
    "curiosidad", "paciencia", "codicia", "vanidad", "timidez",
    "arrepentimiento", "alivio", "sospecha", "prisa", "silencio",
  ],
  5: [
    "llover a cántaros", "ponerse las pilas", "no pegar ojo",
    "costar un ojo de la cara", "ser pan comido", "estar en las nubes",
    "buscar una aguja en un pajar", "matar dos pájaros de un tiro",
    "tener la mosca detrás de la oreja", "quedarse de piedra",
    "estar entre la espada y la pared", "ver las orejas al lobo",
    "poner los pelos de punta", "efecto dominó", "punto de inflexión",
    "media naranja", "flechazo", "amor a primera vista", "mal de ojo",
    "sexto sentido", "instinto", "intuición", "memoria", "olvido",
    "recuerdo", "sueño", "pesadilla", "esperanza",
    "libertad", "justicia", "democracia", "capitalismo", "globalización",
    "inteligencia artificial", "cambio climático", "evolución", "infinito",
    "paradoja", "eternidad", "caos", "entropía", "azar", "privacidad",
    "identidad", "burocracia", "jerarquía", "diplomacia", "hipocresía",
    "nepotismo", "ironía", "sarcasmo", "malentendido", "coincidencia",
    "déjà vu", "utopía", "distopía", "statu quo", "efecto mariposa",
  ],
};
