// Categoría oficial verde: "Difícil. Palabras difíciles."
// Su suelo es más alto que el del resto: el nivel 1 de esta categoría
// equivale aproximadamente a un nivel 3 global. Reconstruida siguiendo la
// textura real de las cartas originales (sustantivos concretos raros,
// cualidades, términos específicos y abstractos anclables), NO abstracción
// filosófica pura sin gancho visual.

export const difficulty = {
  1: [
    "yema", "clara", "corteza", "migaja", "pelusa", "moho", "óxido", "vaho",
    "escarcha", "rocío", "remolino", "eco", "reflejo", "silueta", "grieta",
    "arruga", "cicatriz", "peca", "lunar", "astilla", "serrín", "ceniza",
    "brasa", "hollín", "telaraña", "cáscara", "espina", "hueso de aceituna",
    "veta", "nudo de madera", "burbuja", "espuma", "humo", "chispa", "gota",
    "charco", "goteo", "chorro", "salpicadura", "mancha", "lazo", "pliegue",
    "dobladillo", "costura", "hilo suelto", "cremallera atascada",
    "botón descosido", "raspadura", "muesca", "abolladura", "rebaba",
    "borde afilado", "punta roma", "mota de polvo", "hebra",
  ],
  2: [
    "hectárea", "decibelio", "quilate", "octanaje", "caballo de vapor",
    "voltio", "amperio", "kilovatio", "caloría", "tonelada", "nudo náutico",
    "milla", "legua", "pulgada", "año luz", "latitud", "longitud",
    "meridiano", "paralelo", "ligamento", "cartílago", "menisco", "esternón",
    "clavícula", "rótula", "tímpano", "córnea", "yugular", "aorta", "tendón",
    "vértebra", "muela del juicio", "uña encarnada", "ampolla", "moratón",
    "calambre", "agujetas", "flato", "tortícolis", "lumbago", "migraña",
    "hipo", "mareo", "vértigo", "afluente", "meandro", "barlovento",
    "sotavento", "cenit", "equinoccio", "solsticio", "deshielo", "sequía",
    "aguanieve", "ventisca", "granizo", "marea alta", "marea baja",
    "resaca del mar", "isobara", "frente frío", "anticiclón", "borrasca",
    "capa de ozono", "efecto invernadero",
  ],
  3: [
    "resbaladizo", "áspero", "pegajoso", "hueco", "translúcido", "opaco",
    "borroso", "nítido", "mullido", "crujiente", "rancio", "soso",
    "empalagoso", "tibio", "punzante", "chirriante", "holgado", "ceñido",
    "torcido", "simétrico", "diagonal", "inclinado", "cóncavo",
    "convexo", "denso", "esponjoso", "quebradizo", "elástico", "viscoso",
    "granulado", "liso", "rugoso", "mate", "brillante", "transparente",
    "hermético", "impermeable", "inflamable", "corrosivo", "estéril",
    "caducado", "oxidado", "desgastado", "descolorido", "apelmazado",
    "desconchado", "astillado", "agrietado", "abollado", "desenfocado",
    "descentrado", "desalineado", "inestable", "tambaleante", "endeble",
    "robusto", "mohoso", "grasiento", "pringoso", "escurridizo",
  ],
  4: [
    "propina", "fianza", "hipoteca", "herencia", "coartada", "soborno",
    "multa", "subasta", "huelga", "inflación", "jubilación", "ascenso",
    "despido", "mudanza", "avería", "garantía", "caducidad", "inventario",
    "presupuesto", "cuarentena", "peaje", "aduana", "rebajas", "trueque",
    "monopolio", "patente", "plagio", "censura", "propaganda", "superstición",
    "casualidad", "insomnio", "claustrofobia", "daltonismo", "amnesia",
    "déficit", "superávit", "impuesto", "nómina", "finiquito",
    "indemnización", "comisión", "franquicia", "licitación", "embargo",
    "desahucio", "alquiler", "aval", "usufructo", "prescripción",
    "precedente", "cláusula", "letra pequeña", "periodo de prueba",
    "teletrabajo", "brecha salarial", "techo de cristal",
    "síndrome del impostor", "efecto placebo", "círculo vicioso",
    "cuello de botella", "punto de no retorno", "masa crítica",
  ],
  5: [
    "entropía", "inercia", "relatividad", "causalidad", "probabilidad",
    "aleatoriedad", "redundancia", "ambigüedad", "paradoja", "tautología",
    "dicotomía", "dialéctica", "hipótesis", "axioma", "corolario",
    "inferencia", "sesgo cognitivo", "disonancia cognitiva",
    "efecto mariposa", "dilema del prisionero", "navaja de Occam",
    "caja negra", "statu quo", "punto ciego", "sesgo de confirmación",
    "profecía autocumplida", "obsolescencia programada",
    "burbuja financiera", "pirámide de Ponzi", "mano invisible",
    "capital humano", "plusvalía", "alienación", "hegemonía", "meritocracia",
    "nepotismo", "burocracia", "tecnocracia", "populismo", "demagogia",
    "hipocresía", "ironía", "sarcasmo", "eufemismo", "metáfora",
    "sinestesia", "onomatopeya", "palíndromo", "anacronismo", "serendipia",
    "melancolía", "resiliencia", "empatía", "catarsis", "epifanía",
    "utopía", "distopía", "nihilismo", "estoicismo", "solipsismo",
  ],
};
