// Categoría oficial amarilla: "Objeto. Cosas que se pueden ver o tocar."
// Todo lo de aquí debe ser tangible; la dificultad sube por especificidad,
// por necesitar contexto para distinguirse, o por ser un objeto poco común.

export const object = {
  1: [
    "lápiz", "tijeras", "martillo", "llave", "taza", "cuchara", "tenedor",
    "cuchillo", "plato", "vaso", "botella", "silla", "mesa", "cama", "puerta",
    "ventana", "lámpara", "bombilla", "teléfono", "ordenador", "televisor",
    "reloj", "libro", "gafas", "sombrero", "zapato", "calcetín", "camiseta",
    "pantalón", "paraguas", "mochila", "maleta", "pelota", "globo", "vela",
    "escoba", "cubo", "espejo", "peine", "cepillo de dientes", "jabón",
    "toalla", "pala", "cuerda", "escalera", "bicicleta", "monopatín",
    "guitarra", "tambor", "piano", "cámara", "sartén", "olla", "nevera",
    "horno", "lavadora", "grifo", "bañera", "sofá", "cojín", "manta",
    "alfombra", "cortina", "cuadro", "jarrón", "maceta", "regadera",
    "tirita", "termómetro", "jeringuilla", "guante", "bufanda", "anillo",
    "collar", "corbata", "cinturón", "monedero", "sello", "sobre", "tijera de podar",
  ],
  2: [
    "acordeón", "periscopio", "yunque", "fuelle", "embudo", "veleta",
    "aldaba", "sacacorchos", "rallador", "colador", "exprimidor", "batidora",
    "tostadora", "cafetera italiana", "molinillo de café", "mortero",
    "espumadera", "cucharón", "palillos chinos", "nivel de burbuja",
    "bisagra", "arandela", "tuerca", "muelle", "polea", "engranaje",
    "taladro", "sierra de calar", "soplete", "llave inglesa", "alicates",
    "cincel", "lima", "torno", "estetoscopio", "tensiómetro", "muleta",
    "férula", "gotero", "camilla", "silla de ruedas", "audífono",
    "lupa de joyero", "prismáticos", "sextante", "astrolabio", "brújula",
    "catalejo", "boya", "hidrante", "toldo", "persiana", "mirilla",
    "cortacésped", "desbrozadora", "manguera", "aspersor", "hamaca",
    "saco de dormir", "esterilla", "cantimplora", "hornillo",
    "linterna frontal", "piolet", "crampones", "arnés", "mosquetón",
    "cuerda de escalada", "matamoscas", "pinza de tender", "posavasos",
    "dedal", "alfiletero", "abanico", "candelabro", "farolillo", "trípode",
  ],
  3: [
    "cinturón de seguridad", "airbag", "papel de burbujas",
    "tapa de alcantarilla", "escalera de incendios", "extintor",
    "manguera de bomberos", "contenedor de reciclaje", "cinta transportadora",
    "carrito de la compra", "puerta giratoria", "molinete de metro",
    "barrera de paso a nivel", "chaleco reflectante", "triángulo de emergencia",
    "cadenas para la nieve", "gato hidráulico", "rueda de repuesto",
    "limpiaparabrisas", "retrovisor", "cuentakilómetros", "salpicadero",
    "matrícula", "señal de stop", "badén", "quitamiedos", "parquímetro",
    "reloj de cuco", "caja de música", "metrónomo", "diapasón", "ábaco",
    "máquina de escribir", "gramófono", "proyector de diapositivas",
    "telégrafo", "tocadiscos", "walkman", "disquete", "casete",
    "carrete de fotos", "cámara polaroid", "claqueta", "foco de teatro",
    "telón", "bola de discoteca", "máquina de humo", "mesa de mezclas",
    "diana de dardos", "futbolín", "máquina tragaperras", "flipper",
    "cabina de fotos", "hucha", "caja fuerte", "buzón de sugerencias",
    "hilo dental", "gemelos de camisa", "hombreras", "plantilla ortopédica",
    "corsé", "peluquín", "dentadura postiza", "pata de palo",
    "atrapasueños", "alfombrilla de ratón", "cinta métrica de sastre",
  ],
  4: [
    "calibre", "micrómetro", "teodolito", "higrómetro", "barómetro",
    "anemómetro", "pluviómetro", "sismógrafo", "osciloscopio", "multímetro",
    "cautín", "fusible", "diferencial", "cuadro eléctrico", "transformador",
    "condensador", "resistencia", "placa base", "disipador",
    "tarjeta gráfica", "amortiguador", "rodamiento", "junta tórica",
    "válvula", "émbolo", "pistón", "biela", "cigüeñal", "carburador",
    "radiador", "alternador", "bujía", "catalizador", "turbina", "hélice",
    "timón", "quilla", "cabrestante", "polipasto", "contrapeso", "lastre",
    "sifón", "desagüe", "rebosadero", "purgador", "termostato", "caldera",
    "tornillo de banco", "ganchillo", "huso", "telar", "rueca",
    "devanadera", "guardapolvo", "quitagrapas", "sello de lacre",
    "escuadra de carpintero", "plomada", "compás de puntas", "gubia",
    "formón", "garlopa", "cepillo de carpintero", "serrucho de costilla",
  ],
  5: [
    "membrana", "filamento", "fibra óptica", "microchip", "transistor",
    "diodo", "semiconductor", "superconductor", "aislante", "electrodo",
    "ánodo", "cátodo", "bobina", "solenoide", "imán de neodimio",
    "giroscopio", "acelerómetro", "péndulo de Foucault", "espejo parabólico",
    "prisma dicroico", "lente de Fresnel", "filtro polarizado",
    "rejilla de difracción", "cámara anecoica", "jaula de Faraday",
    "autoclave", "centrifugadora", "liofilizador", "espectrómetro",
    "cromatógrafo", "tomógrafo", "desfibrilador", "marcapasos", "endoscopio",
    "catéter", "stent", "prótesis", "implante coclear", "exoesqueleto",
    "célula fotovoltaica", "termopar", "capacitor variable", "guía de ondas",
    "antena Yagi", "magnetrón", "klistrón", "tubo de vacío", "válvula termoiónica",
    "criostato", "acelerador de partículas", "cámara de niebla",
    "contador Geiger", "dosímetro", "interferómetro", "colimador",
    "micrótomo", "pipeta automática", "agitador magnético", "matraz aforado",
  ],
};
