// Categoría oficial azul: "Persona, lugar o animal. Se incluyen los nombres."
// Los nombres propios son legales según el reglamento de Mattel y son la
// palanca de dificultad principal de esta categoría.

export const person = {
  1: [
    "bombero", "médico", "policía", "cocinero", "payaso", "pirata", "rey",
    "reina", "bruja", "vaquero", "astronauta", "futbolista", "cartero",
    "granjero", "buzo", "ninja", "vampiro", "zombi", "ángel", "bebé",
    "abuelo", "novia", "perro", "gato", "vaca", "cerdo", "oveja", "caballo",
    "gallina", "pato", "ratón", "conejo", "león", "tigre", "oso", "mono",
    "elefante", "jirafa", "cebra", "pingüino", "delfín", "ballena",
    "tiburón", "cocodrilo", "serpiente", "rana", "tortuga", "pez", "búho",
    "águila", "loro", "abeja", "mariposa", "hormiga", "araña", "playa",
    "montaña", "bosque", "desierto", "isla", "ciudad", "granja", "castillo",
    "iglesia", "colegio", "hospital", "parque", "zoo", "circo", "luna",
    "selva", "río", "cueva", "cabra", "gallo", "burro", "camello", "lobo",
    "zorro", "ciervo", "hipopótamo", "rinoceronte", "koala", "panda",
  ],
  2: [
    "socorrista", "azafata", "árbitro", "torero", "monje", "samurái",
    "vikingo", "faraón", "gladiador", "cavernícola", "alquimista", "juglar",
    "mosquetero", "caballero medieval", "gimnasta", "esquiador", "surfista",
    "ciclista", "boxeador", "halterófilo", "jinete", "domador", "malabarista",
    "mimo", "taxista", "camionero", "minero", "leñador", "pescador", "pastor",
    "herrero", "panadero", "carnicero", "peluquero", "dentista", "veterinario",
    "óptico", "sastre", "zapatero", "ornitorrinco", "armadillo", "perezoso",
    "oso hormiguero", "tapir", "suricata", "narval", "manatí", "morsa",
    "foca", "nutria", "castor", "mapache", "zorrillo", "puercoespín", "erizo",
    "topo", "murciélago", "lémur", "gorila", "orangután", "chimpancé",
    "hiena", "chacal", "leopardo", "guepardo", "lince", "puma", "alce",
    "reno", "bisonte", "búfalo", "dromedario", "llama", "alpaca", "tucán",
    "pelícano", "avestruz", "emú", "pavo real", "cisne", "garza", "cigüeña",
    "urraca", "colibrí", "faro", "molino", "acantilado", "cascada", "glaciar",
    "duna", "oasis", "pantano", "arrecife", "volcán", "géiser", "cañón",
    "laguna", "estadio", "aeropuerto", "puerto", "estación de tren",
    "biblioteca", "museo", "teatro", "gimnasio", "mercado", "cementerio",
  ],
  3: [
    "Cleopatra", "Napoleón", "Julio César", "Cristóbal Colón", "Juana de Arco",
    "Robin Hood", "Drácula", "Frankenstein", "Sherlock Holmes", "Don Quijote",
    "Sancho Panza", "Pinocho", "Caperucita Roja", "Blancanieves", "Cenicienta",
    "Rapunzel", "Peter Pan", "Tarzán", "Papá Noel", "Rey Midas",
    "Barba Negra", "Tutankamón", "Espartaco", "Gengis Kan", "Marco Polo",
    "El Cid", "Hércules", "Zeus", "Poseidón", "Medusa", "Minotauro",
    "Rómulo y Remo", "Torre Eiffel", "Taj Mahal", "Stonehenge",
    "Machu Picchu", "Muralla China", "Coliseo", "Sagrada Familia",
    "Cristo Redentor", "Torre de Pisa", "Monte Rushmore", "Petra",
    "Chichén Itzá", "Partenón", "Golden Gate", "Big Ben",
    "Estatua de la Libertad", "Gran Cañón", "Everest", "Polo Norte",
    "Pompeya", "Venecia", "sonámbulo", "náufrago", "polizón", "espía",
    "paparazzi", "aguafiestas", "madrugador", "gorrón", "becario",
    "opositor", "jubilado", "recién casados", "trillizos", "suegra",
    "cuñado", "vecino cotilla", "hombre orquesta", "mujer barbuda",
    "hombre bala", "zurdo", "gemelos", "ahijado",
  ],
  4: [
    "taxidermista", "luthier", "funambulista", "contorsionista", "ventrílocuo",
    "prestidigitador", "sepulturero", "deshollinador", "afilador", "apicultor",
    "logopeda", "quiropráctico", "forense", "notario", "cerrajero", "sommelier",
    "catador", "perfumista", "calígrafo", "restaurador de arte",
    "controlador aéreo", "censor", "mecenas", "heredero", "rehén", "mediador",
    "suplente", "doble de acción", "extra de cine", "autónomo", "funcionario",
    "inspector de hacienda", "perito", "actuario", "epidemiólogo", "sismólogo",
    "paleontólogo", "ornitólogo", "micólogo", "pangolín", "okapi", "casuario",
    "quebrantahuesos", "abubilla", "martín pescador", "frailecillo", "alcatraz",
    "cernícalo", "ñandú", "dugongo", "marsopa", "orca", "pez martillo",
    "pez luna", "rape", "anguila", "galápago", "varano", "axolote", "tritón",
    "salamandra", "musaraña", "comadreja", "garduña", "jineta", "glotón",
    "íbice", "muflón", "gamo", "corzo", "urogallo", "avutarda", "fiordo",
    "istmo", "meseta", "delta", "atolón", "manglar", "tundra", "taiga",
    "estepa", "salina", "marisma", "caldera", "dique seco", "esclusa",
    "catacumbas", "mirador", "área de servicio", "paso a nivel", "rotonda",
    "peaje", "trastero", "buhardilla", "invernadero", "quirófano", "morgue",
    "lavandería", "vestuario",
  ],
  5: [
    "chivo expiatorio", "oveja negra", "alma gemela",
    "lobo con piel de cordero", "talón de Aquiles", "caballo de Troya",
    "canto de sirena", "hombre del saco", "hombre invisible",
    "el hombre de la máscara de hierro",
    "Sísifo", "Ícaro", "Prometeo", "Narciso", "Pandora", "Casandra",
    "Odiseo", "Hades", "Cerbero", "Quimera", "Grifo",
    "Basilisco", "Kraken", "Yeti", "Golem", "Fénix", "Centauro",
    "Esfinge de Tebas", "Leviatán", "Cíclope de la Odisea", "Sócrates", "Platón", "Confucio", "Buda", "Moisés",
    "Caín y Abel", "Rey Salomón", "Sansón", "David y Goliat", "Adán y Eva",
    "los Reyes Magos", "el Flautista de Hamelín", "Mata Hari", "Anne Frank",
    "Utopía",
    "El Dorado", "Shangri-La", "tierra de nadie", "purgatorio", "limbo",
    "Olimpo", "Valhalla", "Arca de Noé", "Torre de Babel", "Muro de Berlín",
    "Ruta de la Seda", "Silicon Valley", "Wall Street",
    "Triángulo de las Bermudas", "Área 51", "agujero negro", "multiverso",
    "línea del ecuador", "meridiano de Greenwich", "huso horario",
    "hemisferio sur", "Cinturón de Fuego", "Atlántida", "Jardín del Edén",
    "la humanidad", "un desconocido", "el vecino del quinto",
  ],
};
