// Categorías temáticas (parte A). El nivel mide lo difícil que es hacer que
// el equipo diga EXACTAMENTE esa palabra, no lo oscuro que sea el dato.

export const movies = {
  1: [
    "Titanic", "Frozen", "Shrek", "Avatar", "Rocky", "Tarzán", "Bambi",
    "Dumbo", "Cars", "Up", "Coco", "Moana", "Aladdín", "Mulán",
    "Ratatouille", "Buscando a Nemo", "Toy Story", "Monstruos S.A.",
    "Los Increíbles", "Madagascar", "Kung Fu Panda", "Ice Age", "Minions",
    "El Rey León", "La Sirenita", "La Bella y la Bestia",
    "El Libro de la Selva", "101 Dálmatas", "Peter Pan", "El Grinch",
  ],
  2: [
    "Jumanji", "Parque Jurásico", "King Kong", "Godzilla", "E.T.",
    "Star Wars", "Indiana Jones", "Regreso al Futuro", "Los Cazafantasmas",
    "Men in Black", "Piratas del Caribe", "Harry Potter",
    "El Señor de los Anillos", "El Hobbit", "Las Crónicas de Narnia",
    "Matrix", "Terminator", "Alien", "Depredador", "Mad Max", "Gladiator",
    "Troya", "300", "Braveheart", "Los Simpson", "Friends",
    "Stranger Things", "La Casa de Papel", "Juego de Tronos", "Breaking Bad",
  ],
  3: [
    "El Padrino", "Pulp Fiction", "Forrest Gump", "Náufrago",
    "El Show de Truman", "Gravity", "Interestelar", "Origen",
    "El Sexto Sentido", "El Club de la Lucha", "Psicosis", "Los Pájaros",
    "El Resplandor", "It", "El Exorcista", "Scream", "Saw", "Parásitos",
    "Joker", "Bohemian Rhapsody", "La La Land", "Mamma Mia", "Grease",
    "Cantando bajo la lluvia", "Casablanca", "El Mago de Oz", "The Office",
    "Black Mirror", "Chernobyl", "Peaky Blinders", "Narcos",
    "The Walking Dead", "Prison Break", "El Juego del Calamar",
    "The Last of Us", "Wednesday",
  ],
  4: [
    "Ciudadano Kane", "Metrópolis", "2001: Una odisea del espacio",
    "La naranja mecánica", "Apocalypse Now", "Taxi Driver",
    "El silencio de los corderos", "Seven", "Memento", "Old Boy",
    "El laberinto del fauno", "Amélie", "Cinema Paradiso",
    "La vida es bella", "El pianista", "La lista de Schindler",
    "Doce hombres sin piedad", "Con faldas y a lo loco",
    "Uno de los nuestros", "Cadena perpetua", "Reservoir Dogs",
    "Trainspotting", "Fargo", "El gran Lebowski", "Whiplash", "Birdman",
    "Her", "Ex Machina", "Blade Runner", "La llegada", "Dune",
    "Oppenheimer", "Los Soprano", "Twin Peaks",
  ],
  5: [
    "Persona", "El séptimo sello", "Ocho y medio", "La dolce vita",
    "Stalker", "Solaris", "El discreto encanto de la burguesía",
    "Un perro andaluz", "Rashomon", "Los siete samuráis",
    "Cuentos de Tokio", "Ladrón de bicicletas", "El espíritu de la colmena",
    "Viridiana", "Tesis", "Mulholland Drive", "Carretera perdida",
    "Eraserhead", "El árbol de la vida", "Melancolía",
    "El caballo de Turín", "El acorazado Potemkin", "Nosferatu",
    "El gabinete del doctor Caligari", "Amanecer", "Ordet", "Andrei Rublev",
    "Sacrificio", "La pasión de Juana de Arco", "Jeanne Dielman",
  ],
};

export const famous = {
  1: [
    "Messi", "Cristiano Ronaldo", "Shakira", "Beyoncé", "Rihanna",
    "Michael Jackson", "Elvis Presley", "Madonna", "Lady Gaga",
    "Taylor Swift", "Bad Bunny", "Rosalía", "Kim Kardashian", "Elon Musk",
    "Bill Gates", "Steve Jobs", "Donald Trump", "Barack Obama",
    "Papa Francisco", "Rafa Nadal", "Pau Gasol", "LeBron James",
    "Michael Jordan", "Usain Bolt", "Muhammad Ali", "Mike Tyson",
    "Maradona", "Pelé", "Neymar", "Mbappé",
  ],
  2: [
    "Albert Einstein", "Isaac Newton", "Charles Darwin", "Galileo Galilei",
    "Marie Curie", "Nikola Tesla", "Thomas Edison", "Leonardo da Vinci",
    "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí", "Frida Kahlo",
    "Miguel Ángel", "Beethoven", "Mozart", "Bach", "Shakespeare",
    "Cervantes", "Mark Twain", "Charles Dickens", "Gandhi",
    "Nelson Mandela", "Martin Luther King", "Abraham Lincoln",
    "Winston Churchill", "Che Guevara", "Fidel Castro", "Neil Armstrong",
  ],
  3: [
    "Freddie Mercury", "John Lennon", "Paul McCartney", "Bob Marley",
    "Jimi Hendrix", "Kurt Cobain", "David Bowie", "Prince", "Amy Winehouse",
    "Whitney Houston", "Frank Sinatra", "Charlie Chaplin", "Marilyn Monroe",
    "Audrey Hepburn", "Alfred Hitchcock", "Steven Spielberg",
    "Quentin Tarantino", "Tim Burton", "Stanley Kubrick", "Woody Allen",
    "Robin Williams", "Jim Carrey", "Mr. Bean", "Arnold Schwarzenegger",
    "Sylvester Stallone", "Bruce Lee", "Jackie Chan", "Keanu Reeves",
    "Tom Cruise", "Brad Pitt", "Angelina Jolie", "Leonardo DiCaprio",
    "Meryl Streep", "Penélope Cruz", "Javier Bardem", "Antonio Banderas",
    "Pedro Almodóvar",
  ],
  4: [
    "Stephen Hawking", "Alan Turing", "Ada Lovelace", "Rosalind Franklin",
    "Carl Sagan", "Jane Goodall", "Jacques Cousteau", "David Attenborough",
    "Noam Chomsky", "Sigmund Freud", "Carl Jung", "Karl Marx", "Adam Smith",
    "John Maynard Keynes", "Immanuel Kant", "Friedrich Nietzsche",
    "Jean-Paul Sartre", "Simone de Beauvoir", "Hannah Arendt",
    "Virginia Woolf", "Jane Austen", "Emily Dickinson",
    "Gabriel García Márquez", "Jorge Luis Borges", "Pablo Neruda",
    "Federico García Lorca", "Isabel Allende", "Haruki Murakami",
    "J.R.R. Tolkien", "George Orwell", "Agatha Christie", "Edgar Allan Poe",
    "Franz Kafka", "Dostoyevski", "León Tolstói",
  ],
  5: [
    "Rasputín", "Nostradamus", "Maquiavelo", "Torquemada", "Calígula",
    "Nerón", "Atila", "Ramsés II", "Hatshepsut", "Boudica", "Mansa Musa",
    "Ibn Battuta", "Averroes", "Hipatia", "Arquímedes", "Pitágoras",
    "Euclides", "Copérnico", "Kepler", "Tycho Brahe", "Paracelso",
    "Gregor Mendel", "Louis Pasteur", "Alexander Fleming", "Lavoisier",
    "Mendeléyev", "Michael Faraday", "James Clerk Maxwell", "Schrödinger",
    "Heisenberg", "Niels Bohr", "Oppenheimer", "Von Neumann", "Kurt Gödel",
    "Ramanujan", "Leonhard Euler", "Carl Gauss", "Fibonacci",
  ],
};

export const insect = {
  1: [
    "hormiga", "abeja", "mariposa", "mosca", "mosquito", "araña",
    "escarabajo", "saltamontes", "libélula", "avispa", "oruga", "gusano",
    "caracol", "ciempiés", "cucaracha", "grillo", "luciérnaga", "mariquita",
    "pulga", "piojo",
  ],
  2: [
    "mantis religiosa", "escorpión", "tarántula", "avispón", "abejorro",
    "tábano", "polilla", "chinche", "garrapata", "ácaro", "termita",
    "hormiga reina", "zángano", "larva", "crisálida", "capullo", "babosa",
    "lombriz", "milpiés", "tijereta", "cigarra", "escarabajo pelotero",
    "mosca tsetsé", "araña de agua", "avispa alfarera",
  ],
  3: [
    "escarabajo rinoceronte", "escarabajo Hércules", "insecto palo",
    "insecto hoja", "hormiga león", "avispa parásita", "araña saltarina",
    "viuda negra", "tarántula Goliat", "araña de rincón", "araña lobo",
    "opilión", "pulgón", "cochinilla", "gorgojo", "polilla de la ropa",
    "gusano de seda", "abeja carpintera", "mosca de la fruta", "efímera",
    "zapatero de agua", "escarabajo tigre", "mariposa monarca",
    "mariposa atlas", "esfinge colibrí", "chinche de agua gigante",
  ],
  4: [
    "coleóptero", "lepidóptero", "himenóptero", "díptero", "ortóptero",
    "hemíptero", "odonato", "isóptero", "metamorfosis completa",
    "exoesqueleto", "quitina", "antena", "palpo", "mandíbula", "ovipositor",
    "aguijón", "élitro", "tórax", "abdomen", "espiráculo", "hemolinfa",
    "muda", "diapausa", "feromona", "polinización", "apicultura",
    "panal hexagonal", "danza de la abeja", "colonia de hormigas",
    "ojo compuesto",
  ],
  5: [
    "escarabajo joya", "escarabajo bombardero", "escarabajo violín",
    "escarabajo titán", "ciervo volante", "gorgojo jirafa",
    "chinche asesina", "chinche acorazada", "mosca linterna",
    "membrácido", "cigarra periódica", "hormiga bala",
    "hormiga cortadora de hojas", "hormiga tejedora", "avispa icneumón",
    "avispa esmeralda", "abeja orquídea", "abeja cortadora de hojas",
    "mosca grulla", "escorpión látigo", "vinagrillo", "solífugo",
    "pseudoescorpión", "ácaro terciopelo", "araña pavo real",
    "araña cangrejo", "araña trampilla", "tarántula azul cobalto",
    "escolopendra gigante", "colémbolo", "pececillo de plata",
    "mantis orquídea", "mantis fantasma", "grillo topo", "pulgón lanudo",
  ],
};

export const food = {
  1: [
    "pizza", "hamburguesa", "perrito caliente", "patatas fritas", "bocadillo",
    "sándwich", "tarta", "helado", "chocolate", "caramelo", "piruleta",
    "palomitas", "galleta", "donut", "croissant", "pan", "queso",
    "huevo frito", "tortilla", "paella", "espaguetis", "sopa", "ensalada",
    "manzana", "plátano", "naranja", "uvas", "fresa", "sandía", "piña",
    "limón", "zanahoria", "tomate", "patata", "cebolla", "maíz", "leche",
    "café", "té", "zumo", "refresco", "cerveza", "vino",
  ],
  2: [
    "sushi", "ramen", "taco", "burrito", "nachos", "guacamole", "kebab",
    "falafel", "hummus", "gazpacho", "tortilla de patatas", "croquetas",
    "empanada", "churros", "flan", "natillas", "arroz con leche",
    "crema catalana", "tiramisú", "brownie", "tarta de queso", "gofre",
    "crepe", "torrija", "bagel", "pretzel", "baguette", "chapata",
    "mortadela", "chorizo", "jamón serrano", "salchichón", "morcilla",
    "longaniza", "panceta",
  ],
  3: [
    "risotto", "lasaña", "canelones", "ñoquis", "ravioli", "carbonara",
    "pesto", "boloñesa", "bechamel", "alioli", "pisto", "fabada", "cocido",
    "callos", "rabo de toro", "pulpo a la gallega", "bacalao al pil pil",
    "marmitako", "escalivada", "calçots", "pan con tomate", "migas",
    "salmorejo", "ajoblanco", "porrusalda", "sobrasada", "cachopo",
    "pincho moruno", "bocata de calamares", "tarta de Santiago",
    "roscón de Reyes", "polvorones", "turrón", "mazapán", "sopa de ajo",
  ],
  4: [
    "mollejas", "carrillera", "jarrete", "solomillo Wellington",
    "steak tartar", "carpaccio", "ceviche", "escabeche de perdiz",
    "civet de liebre", "cassoulet", "coq au vin", "bullabesa", "borsch",
    "gulash", "strogonoff", "musaca", "baklava", "halva", "mochi",
    "dorayaki", "okonomiyaki", "takoyaki", "bibimbap", "pad thai",
    "laksa", "rendang", "injera", "tayín", "cuscús", "kimchi", "miso",
    "natto", "tempeh", "kombucha", "kéfir", "vermú", "sidra natural",
    "hidromiel", "absenta", "ratafía", "orujo", "pacharán", "horchata",
  ],
  5: [
    "sobremesa", "tapeo", "picoteo", "antojo", "atracón", "empacho",
    "gula", "hambre", "sed", "apetito", "inapetencia", "saciedad",
    "digestión", "ayuno", "bufé libre", "régimen", "sobrepeso", "umami",
    "intolerancia a la lactosa", "celiaquía", "alergia al marisco",
    "cadena de frío", "fecha de caducidad", "kilómetro cero",
    "comercio justo", "dieta mediterránea", "desperdicio alimentario",
    "menú degustación", "estrella Michelin", "media ración", "sobras",
    "receta de la abuela", "punto de sal", "al dente", "a punto de nieve",
    "maridaje", "denominación de origen", "cata a ciegas",
  ],
};

export const animal = {
  1: [
    "perro", "gato", "vaca", "cerdo", "oveja", "cabra", "caballo", "gallina",
    "gallo", "pato", "ganso", "pavo", "conejo", "ratón", "rata", "león",
    "tigre", "oso", "lobo", "zorro", "ciervo", "elefante", "jirafa", "cebra",
    "hipopótamo", "rinoceronte", "mono", "gorila", "camello", "canguro",
    "koala", "panda", "pingüino", "delfín", "ballena", "tiburón", "pulpo",
    "cangrejo", "tortuga", "serpiente", "cocodrilo", "rana", "búho",
    "águila", "loro", "cisne", "flamenco", "avestruz",
  ],
  2: [
    "nutria", "castor", "tejón", "comadreja", "marta", "hurón", "mapache",
    "zorrillo", "puercoespín", "erizo", "topo", "musaraña", "murciélago",
    "ardilla", "marmota", "lémur", "orangután", "chimpancé", "babuino",
    "mandril", "suricata", "perezoso", "armadillo", "oso hormiguero",
    "tapir", "jabalí", "bisonte", "búfalo", "alce", "reno", "antílope",
    "gacela", "ñu", "impala", "guepardo", "leopardo", "jaguar", "puma",
    "lince", "hiena", "chacal", "dingo",
  ],
  3: [
    "ornitorrinco", "equidna", "wombat", "demonio de Tasmania", "quokka",
    "okapi", "dugongo", "manatí", "narval", "beluga", "orca", "marsopa",
    "morsa", "foca monje", "león marino", "pangolín", "aye-aye", "tarsero",
    "loris", "gálago", "binturong", "coatí", "kinkajú", "serval", "caracal",
    "ocelote", "margay", "gato de Pallas", "oso malayo", "oso de anteojos",
    "glotón", "íbice", "muflón", "gamo", "corzo",
  ],
  4: [
    "quebrantahuesos", "abubilla", "martín pescador", "frailecillo",
    "alcatraz", "cormorán", "cernícalo", "halcón peregrino", "búho nival",
    "cárabo", "autillo", "mochuelo", "avutarda", "urogallo", "sisón",
    "alcaraván", "chotacabras", "vencejo", "colibrí", "tucán", "quetzal",
    "ave del paraíso", "casuario", "ñandú", "emú", "kiwi", "kakapo",
    "arrendajo", "urraca", "chova", "camachuelo", "jilguero", "verderón",
    "lavandera", "curruca", "abejaruco",
  ],
  5: [
    "celacanto", "pez luna", "rape abisal", "pez víbora", "tiburón duende",
    "tiburón anguila", "calamar gigante", "nautilus", "axolote",
    "tritón crestado", "salamandra gigante", "cecilia", "tuátara",
    "varano de Komodo", "camaleón de Parson", "gecko satánico",
    "serpiente marina", "anaconda verde", "taipán", "mamba negra",
    "cobra real", "boa constrictor", "tortuga laúd",
    "tiburón de Groenlandia", "medusa inmortal", "tardígrado", "rotífero",
    "nematodo", "lamprea", "mixino", "pez pulmonado", "pepino de mar",
    "estrella de mar", "erizo de mar", "caballito de mar",
  ],
};

export const occupation = {
  1: [
    "médico", "bombero", "policía", "profesor", "cocinero", "camarero",
    "cartero", "taxista", "peluquero", "dentista", "enfermero", "mecánico",
    "fontanero", "electricista", "carpintero", "pintor", "albañil",
    "jardinero", "granjero", "pescador", "panadero", "carnicero", "piloto",
    "azafata", "marinero", "soldado", "juez", "abogado", "futbolista",
    "cantante", "actor", "bailarín", "payaso", "mago", "astronauta",
    "científico", "veterinario", "arquitecto", "ingeniero", "programador",
  ],
  2: [
    "socorrista", "árbitro", "entrenador", "fisioterapeuta", "nutricionista",
    "psicólogo", "farmacéutico", "óptico", "podólogo", "matrona", "celador",
    "revisor", "conductor de autobús", "camionero", "repartidor",
    "mozo de almacén", "cajero", "dependiente", "escaparatista", "modista",
    "sastre", "zapatero", "joyero", "relojero", "herrero", "soldador",
    "cerrajero", "cristalero", "tapicero", "ebanista", "anticuario",
    "librero", "bibliotecario", "traductor", "intérprete",
  ],
  3: [
    "perito", "actuario", "notario", "registrador", "gestor", "asesor fiscal",
    "auditor", "contable", "tasador", "agente inmobiliario",
    "corredor de seguros", "analista financiero", "consultor",
    "community manager", "diseñador gráfico", "luthier",
    "afinador de pianos", "campanero", "deshollinador", "afilador",
    "tonelero", "alfarero", "ceramista", "vidriero", "orfebre",
    "encuadernador", "calígrafo", "ilustrador", "animador", "guionista",
    "montador", "técnico de sonido", "operador de cámara", "regidor",
  ],
  4: [
    "taxidermista", "embalsamador", "sepulturero", "forense", "criminólogo",
    "artificiero", "buzo industrial", "soldador submarino",
    "limpiador de rascacielos", "montador de aerogeneradores",
    "controlador aéreo", "práctico de puerto", "piloto de pruebas",
    "catador de té", "sommelier", "perfumista", "enólogo", "apicultor",
    "halconero", "adiestrador canino", "guarda forestal", "geólogo",
    "sismólogo", "vulcanólogo", "glaciólogo", "espeleólogo",
    "arqueólogo submarino", "paleontólogo", "epidemiólogo",
  ],
  5: [
    "pregonero", "sereno", "aguador", "farolero", "cardador", "batanero",
    "hojalatero", "estañador", "peletero", "curtidor", "tintorero",
    "escribano", "amanuense", "copista", "iluminador de manuscritos",
    "tipógrafo", "linotipista", "cajista", "corrector de estilo",
    "documentalista", "paleógrafo", "heraldista", "genealogista",
    "numismático", "filatelista", "vexilólogo", "organero", "campanólogo",
    "sogero", "colchonero",
  ],
};

export const musicalInstrument = {
  1: [
    "guitarra", "piano", "violín", "tambor", "flauta", "trompeta", "saxofón",
    "batería", "arpa", "acordeón", "pandereta", "maracas", "triángulo",
    "xilófono", "armónica", "ukelele", "bajo", "teclado", "platillos", "gong",
  ],
  2: [
    "violonchelo", "contrabajo", "viola", "clarinete", "oboe", "fagot",
    "trombón", "tuba", "trompa", "corneta", "flautín", "órgano", "banjo",
    "mandolina", "sitar", "balalaica", "laúd", "cítara", "gaita", "dulzaina",
    "ocarina", "kalimba", "marimba", "vibráfono", "timbal", "bongó", "conga",
    "djembé", "cajón flamenco", "castañuelas",
  ],
  3: [
    "fliscorno", "bombardino", "saxofón barítono", "clarinete bajo",
    "corno inglés", "contrafagot", "clavicémbalo", "espineta", "clavicordio",
    "fortepiano", "celesta", "glockenspiel", "carillón", "sintetizador",
    "caja de ritmos", "vocoder", "pedal steel", "dobro", "charango",
    "cuatro venezolano", "bandurria", "bouzouki", "oud", "darbuka",
    "tabla india", "pandeiro", "cuíca", "güiro", "claves",
  ],
  4: [
    "zanfona", "viola da gamba", "tiorba", "archilaúd", "serpentón",
    "sacabuche", "cromorno", "chirimía", "órgano positivo", "salterio",
    "monocordio", "trompa marina", "hidraulis", "arpa eólica",
    "armónica de cristal", "órgano de tubos", "virginal", "rabel",
    "cornamusa", "flauta de pico tenor", "traverso barroco",
    "lira da braccio", "shofar", "buccina", "regal",
  ],
  5: [
    "nyckelharpa", "hardanger", "erhu", "guzheng", "pipa", "koto",
    "shamisen", "shakuhachi", "didgeridoo", "berimbau", "guimbarda",
    "hang drum", "waterphone", "ondas Martenot", "theremín",
    "cristal Baschet", "launeddas", "duduk", "ney", "zurna", "kaval",
    "sheng", "khaen", "morin khuur", "sarangi", "santur", "kora", "balafón",
    "mbira", "steelpan", "gamelán", "angklung",
  ],
};
