// Categorías temáticas (parte B).

export const song = {
  1: [
    "Cumpleaños feliz", "Feliz Navidad", "Macarena", "Despacito",
    "Waka Waka", "La Bamba", "Bailando", "Gasolina", "Vivir mi vida",
    "Danza Kuduro", "Baby Shark", "Let It Go", "YMCA", "We Will Rock You",
    "Happy", "Shape of You", "Thriller", "Billie Jean",
    "Bohemian Rhapsody", "La Cucaracha",
  ],
  2: [
    "Imagine", "Yesterday", "Hey Jude", "Let It Be", "Wonderwall", "Creep",
    "Smells Like Teen Spirit", "Nothing Else Matters", "Enter Sandman",
    "Highway to Hell", "Back in Black", "Sweet Child o' Mine",
    "Stairway to Heaven", "Hotel California", "Sweet Home Alabama",
    "Wish You Were Here", "Another Brick in the Wall", "Purple Rain",
    "Like a Rolling Stone", "Born to Run", "Livin' on a Prayer",
    "I Will Survive", "Dancing Queen", "Africa", "Take On Me",
  ],
  3: [
    "Mediterráneo", "Entre dos aguas", "Volver", "Bésame mucho",
    "Cielito lindo", "Guantanamera", "El cóndor pasa", "Oye cómo va",
    "Chan chan", "Lágrimas negras", "Malagueña salerosa",
    "Alfonsina y el mar", "Gracias a la vida", "Todo cambia", "La Llorona",
    "Cucurrucucú paloma", "Sabor a mí", "Un beso y una flor",
    "Un velero llamado libertad", "La chica de ayer", "Maldito duende",
    "Entre dos tierras", "Insurrección", "Hoy no me puedo levantar",
    "Bailar pegados", "La flaca", "Sin documentos", "Zapatillas",
  ],
  4: [
    "Las cuatro estaciones", "Claro de luna", "Para Elisa", "Marcha turca",
    "El vuelo del moscardón", "Danza del sable", "Bolero de Ravel",
    "Carmina Burana", "Ave María", "Canon de Pachelbel",
    "La cabalgata de las valquirias", "Marcha fúnebre", "Rapsodia húngara",
    "Gymnopédie n.º 1", "Nocturno op. 9 n.º 2", "El lago de los cisnes",
    "El cascanueces", "La consagración de la primavera", "Peer Gynt",
    "En la gruta del rey de la montaña", "Adagio de Albinoni",
    "Concierto de Aranjuez", "El Danubio azul", "Obertura 1812",
    "Sinfonía del Nuevo Mundo", "Rapsodia en azul",
  ],
  5: [
    "A Love Supreme", "So What", "Take Five", "Giant Steps",
    "Round Midnight", "Blue in Green", "My Favorite Things", "Naima",
    "Birdland", "Chameleon", "Watermelon Man", "Cantaloupe Island",
    "Maiden Voyage", "Footprints", "All Blues", "Blue Bossa", "Nefertiti",
    "Bitches Brew", "In a Silent Way", "Sketches of Spain",
    "The Sidewinder", "Moanin'", "Song for My Father", "Manteca",
    "Afro Blue", "Autumn Leaves", "Body and Soul", "Summertime",
  ],
};

export const game = {
  1: [
    "ajedrez", "damas", "parchís", "oca", "dominó", "póker", "bingo",
    "dardos", "billar", "futbolín", "ping pong", "tres en raya",
    "escondite", "pilla pilla", "comba", "canicas", "yoyó", "peonza",
    "rayuela", "Monopoly", "Twister", "Jenga", "Uno", "Cluedo", "Trivial",
    "Scrabble", "Pictionary", "Tetris", "Pac-Man", "Mario Bros",
    "Minecraft", "Fortnite", "FIFA", "Candy Crush",
  ],
  2: [
    "Risk", "Catan", "Carcassonne", "Dixit", "Time's Up", "Party & Co",
    "Tabú", "Hundir la flota", "Conecta 4", "Operación", "Quién es quién",
    "Mastermind", "Rummikub", "Backgammon", "Go", "Mahjong", "Solitario",
    "Buscaminas", "Sudoku", "Crucigrama", "Sopa de letras", "Puzzle",
    "Cubo de Rubik", "Simon", "Tamagotchi", "Game Boy", "PlayStation",
    "Nintendo Switch", "Pinball", "Angry Birds",
  ],
  3: [
    "Pandemic", "Terraforming Mars", "Wingspan", "Azul", "Splendor",
    "7 Wonders", "Dominion", "Agricola", "Puerto Rico", "Scythe",
    "Gloomhaven", "Twilight Imperium", "Root", "Brass", "Ticket to Ride",
    "Codenames", "Hanabi", "The Crew", "Exploding Kittens", "Hombres Lobo",
    "Escape room", "Dungeons & Dragons", "Magic: The Gathering",
    "Yu-Gi-Oh", "Pokémon TCG", "Warhammer", "Virus", "Bang!",
  ],
  4: [
    "The Legend of Zelda", "Metroid", "Castlevania", "Mega Man",
    "Street Fighter", "Mortal Kombat", "Doom", "Quake", "Half-Life",
    "Portal", "BioShock", "Dark Souls", "Bloodborne", "Elden Ring",
    "Hollow Knight", "Celeste", "Braid", "Limbo", "Inside", "Journey",
    "Shadow of the Colossus", "Ico", "Silent Hill", "Resident Evil",
    "Metal Gear Solid", "Final Fantasy", "Chrono Trigger", "EarthBound",
    "Undertale", "Stardew Valley", "Factorio", "RimWorld",
    "Kerbal Space Program", "Katamari Damacy",
  ],
  5: [
    "NetHack", "Rogue", "Colossal Cave Adventure", "Zork", "Pong",
    "Spacewar!", "Tennis for Two", "Oregon Trail", "Myst", "Riven",
    "Grim Fandango", "Day of the Tentacle", "Monkey Island", "Loom",
    "Another World", "Flashback", "Prince of Persia", "Lemmings",
    "Populous", "Civilization", "SimCity", "Theme Hospital", "Dune II",
    "Command & Conquer", "Age of Empires", "StarCraft",
    "Total Annihilation", "Homeworld", "Elite", "X-COM",
    "Jagged Alliance", "Fallout", "Planescape: Torment", "Baldur's Gate",
    "Ultima", "Wizardry", "Might and Magic",
  ],
};

export const country = {
  1: [
    "España", "Francia", "Italia", "Portugal", "Alemania", "Reino Unido",
    "Estados Unidos", "México", "Brasil", "Argentina", "China", "Japón",
    "India", "Rusia", "Egipto", "Australia", "Canadá", "Marruecos",
    "Grecia", "Suiza",
  ],
  2: [
    "Países Bajos", "Bélgica", "Austria", "Suecia", "Noruega", "Dinamarca",
    "Finlandia", "Irlanda", "Escocia", "Polonia", "Chequia", "Hungría",
    "Rumanía", "Bulgaria", "Croacia", "Serbia", "Turquía", "Israel",
    "Arabia Saudí", "Irán", "Irak", "Pakistán", "Tailandia", "Vietnam",
    "Corea del Sur", "Indonesia", "Filipinas", "Nueva Zelanda",
    "Sudáfrica", "Nigeria", "Kenia", "Etiopía", "Chile", "Perú",
    "Colombia", "Venezuela", "Cuba", "Jamaica",
  ],
  3: [
    "Islandia", "Groenlandia", "Estonia", "Letonia", "Lituania",
    "Bielorrusia", "Ucrania", "Moldavia", "Eslovaquia", "Eslovenia",
    "Bosnia y Herzegovina", "Montenegro", "Albania", "Macedonia del Norte",
    "Chipre", "Malta", "Luxemburgo", "Liechtenstein", "Andorra", "Mónaco",
    "San Marino", "Ciudad del Vaticano", "Georgia", "Armenia",
    "Azerbaiyán", "Kazajistán", "Uzbekistán", "Mongolia", "Nepal",
    "Bután", "Sri Lanka", "Bangladés", "Birmania", "Camboya", "Laos",
    "Malasia", "Singapur", "Taiwán",
  ],
  4: [
    "Surinam", "Guyana", "Belice", "Honduras", "Nicaragua", "Costa Rica",
    "Panamá", "Paraguay", "Uruguay", "Bolivia", "Ecuador", "Haití",
    "República Dominicana", "Trinidad y Tobago", "Barbados", "Bahamas",
    "Senegal", "Malí", "Níger", "Chad", "Sudán", "Somalia", "Eritrea",
    "Yibuti", "Uganda", "Ruanda", "Burundi", "Tanzania", "Zambia",
    "Zimbabue", "Botsuana", "Namibia", "Angola", "Mozambique",
    "Madagascar", "Mauricio", "Seychelles",
  ],
  5: [
    "Kirguistán", "Tayikistán", "Turkmenistán", "Afganistán", "Yemen",
    "Omán", "Baréin", "Catar", "Kuwait", "Líbano", "Siria", "Jordania",
    "Timor Oriental", "Brunéi", "Papúa Nueva Guinea", "Vanuatu", "Fiyi",
    "Samoa", "Tonga", "Tuvalu", "Kiribati", "Nauru", "Palaos",
    "Islas Marshall", "Micronesia", "Islas Salomón", "Comoras",
    "Cabo Verde", "Santo Tomé y Príncipe", "Guinea Ecuatorial", "Gabón",
    "República Centroafricana", "Sudán del Sur", "Lesoto", "Esuatini",
    "Burkina Faso", "Benín", "Togo", "Costa de Marfil", "Ghana",
    "Liberia", "Sierra Leona", "Guinea-Bisáu", "Gambia", "Mauritania",
  ],
};

export const app = {
  1: [
    "WhatsApp", "Instagram", "YouTube", "Google", "Facebook", "TikTok",
    "Twitter", "Netflix", "Spotify", "Amazon", "Gmail", "Wikipedia",
    "Zoom", "Skype", "Telegram", "Snapchat", "LinkedIn", "Pinterest",
    "Twitch", "Uber",
  ],
  2: [
    "Waze", "Google Maps", "Booking", "Airbnb", "Tripadvisor", "eBay",
    "AliExpress", "Shein", "PayPal", "Bizum", "Revolut", "Wallapop",
    "Vinted", "Glovo", "Just Eat", "Cabify", "BlaBlaCar", "Tinder",
    "Bumble", "Duolingo", "Strava", "Shazam", "SoundCloud", "Deezer",
    "HBO Max", "Disney+", "Prime Video", "Filmin",
  ],
  3: [
    "Discord", "Slack", "Notion", "Trello", "Asana", "Jira", "Figma",
    "Canva", "Miro", "Dropbox", "Google Drive", "OneDrive", "iCloud",
    "GitHub", "GitLab", "Stack Overflow", "Reddit", "Quora", "Medium",
    "Substack", "Patreon", "Kickstarter", "Etsy", "Shopify", "WordPress",
    "Wix", "Mailchimp", "Calendly",
  ],
  4: [
    "Docker Hub", "npm", "PyPI", "Hugging Face", "Kaggle",
    "Google Colab", "Jupyter", "Replit", "Vercel", "Netlify", "Heroku",
    "Cloudflare", "Firebase", "Supabase", "Postman", "Sentry", "Datadog",
    "Grafana", "Prometheus", "Terraform", "Ansible", "Homebrew",
    "Stack Exchange", "CodePen", "JSFiddle", "Bitbucket",
  ],
  5: [
    "Internet Archive", "Wayback Machine", "Project Gutenberg", "arXiv",
    "PubMed", "JSTOR", "Google Scholar", "Zenodo", "OpenStreetMap",
    "Wikidata", "Wikimedia Commons", "Tor Browser", "Mastodon", "Signal",
    "Neocities", "GeoCities", "SourceForge", "Pastebin", "Craigslist",
    "Hacker News", "Product Hunt", "Goodreads", "Letterboxd", "Discogs",
    "Bandcamp", "Last.fm", "MyAnimeList", "IMDb", "Rotten Tomatoes",
    "Metacritic", "Anki", "Obsidian", "Zotero", "Overleaf",
    "Wolfram Alpha", "Desmos", "GeoGebra", "Archive of Our Own",
  ],
};

export const brand = {
  1: [
    "Coca-Cola", "Pepsi", "McDonald's", "Burger King", "Nike", "Adidas",
    "Apple", "Samsung", "Microsoft", "Sony", "Nintendo", "Lego", "Barbie",
    "Disney", "Ferrari", "Mercedes", "BMW", "Toyota", "Ford", "Ikea",
    "Zara", "H&M", "Lidl", "Mercadona", "Nutella", "Kinder", "Oreo",
    "Pringles", "Fanta", "Nestlé", "Danone", "Colgate", "Gillette",
    "Puma", "Levi's", "Rolex", "Chanel", "Lacoste",
  ],
  2: [
    "Starbucks", "Subway", "KFC", "Domino's", "Telepizza", "Heinz",
    "Kellogg's", "Milka", "Toblerone", "Ferrero Rocher", "Haribo",
    "Chupa Chups", "Lay's", "Doritos", "Red Bull", "Monster", "Gatorade",
    "Aquarius", "Schweppes", "Estrella Damm", "Mahou", "San Miguel",
    "Heineken", "Corona", "Bacardí", "Absolut", "Jack Daniel's",
    "Johnnie Walker", "Moët & Chandon", "Reebok",
  ],
  3: [
    "Bosch", "Siemens", "Philips", "Braun", "Dyson", "Roomba", "Nespresso",
    "Moulinex", "Tefal", "Pyrex", "Tupperware", "Thermomix", "Decathlon",
    "Salomon", "The North Face", "Patagonia", "Columbia", "Timberland",
    "Dr. Martens", "Converse", "Vans", "New Balance", "Asics",
    "Under Armour", "Fjällräven", "Osprey", "Garmin", "Suunto", "Casio",
  ],
  4: [
    "Bloomberg", "Reuters", "McKinsey", "Deloitte", "PwC", "KPMG",
    "Accenture", "Goldman Sachs", "JP Morgan", "BlackRock", "Vanguard",
    "Visa", "Mastercard", "American Express", "Stripe", "Salesforce",
    "Oracle", "SAP", "IBM", "Intel", "AMD", "Nvidia", "Qualcomm", "ARM",
    "TSMC", "ASML", "Foxconn", "Bayer", "Pfizer", "Roche",
  ],
  5: [
    "Maersk", "DHL", "FedEx", "UPS", "Kuehne+Nagel", "Cargill",
    "Glencore", "Rio Tinto", "BHP", "Vale", "Schlumberger", "Halliburton",
    "Caterpillar", "Komatsu", "John Deere", "Vestas", "Ørsted", "Alstom",
    "Bombardier", "Embraer", "Rolls-Royce", "Safran", "Thales",
    "Leonardo", "Airbus", "Boeing", "Honeywell", "Emerson", "ABB",
    "Schneider Electric",
  ],
};

export const heroe = {
  1: [
    "Superman", "Batman", "Spider-Man", "Hulk", "Iron Man",
    "Capitán América", "Thor", "Wonder Woman", "Flash", "Aquaman",
    "Robin", "Catwoman", "Joker", "Venom", "Lobezno", "Deadpool",
    "Viuda Negra", "Ojo de Halcón", "Doctor Extraño", "Ant-Man",
  ],
  2: [
    "Black Panther", "Capitana Marvel", "Star-Lord", "Groot",
    "Rocket Raccoon", "Gamora", "Drax", "Nebula", "Falcon",
    "Soldado de Invierno", "Bruja Escarlata", "Visión", "Mercurio",
    "Cíclope", "Tormenta", "Jean Grey", "Bestia", "Rondador Nocturno",
    "Coloso", "Magneto", "Profesor X", "Mística", "Linterna Verde",
    "Cyborg", "Shazam", "Supergirl", "Batgirl", "Nightwing", "Arlequina",
    "Pingüino", "Enigma", "Espantapájaros", "Bane", "Dos Caras",
  ],
  3: [
    "Daredevil", "Jessica Jones", "Luke Cage", "Puño de Hierro",
    "Castigador", "Motorista Fantasma", "Blade", "Moon Knight",
    "Estela Plateada", "Galactus", "Thanos", "Ultrón", "Loki", "Hela",
    "Doctor Muerte", "Duende Verde", "Doctor Octopus", "Rino", "Buitre",
    "Lagarto", "Kraven", "Mysterio", "Electro", "Hombre de Arena",
    "Carnage", "Morbius", "Zatanna", "Constantine", "La Cosa del Pantano",
    "Deathstroke", "Lobo", "Darkseid", "Ra's al Ghul",
  ],
  4: [
    "Rorschach", "Doctor Manhattan", "Ozymandias", "Búho Nocturno",
    "El Comediante", "Espectro de Seda", "V de Vendetta", "Hellboy",
    "Abe Sapien", "Spawn", "Morfeo", "Muerte de los Eternos", "Delirio",
    "Destrucción", "Deseo", "Juez Dredd", "Tank Girl", "Preacher",
    "Spider Jerusalem", "Invencible", "Omni-Man", "Patrulla Condenada",
    "Animal Man", "Mister Milagro", "Adam Warlock", "Nova", "Sentry",
    "Hyperion", "Namor", "Ka-Zar",
  ],
  5: [
    "Mazinger Z", "Astro Boy", "Ultraman", "Kamen Rider", "Goldorak",
    "One Punch Man", "All Might", "Deku", "Mob", "Meliodas", "Goku",
    "Vegeta", "Luffy", "Ichigo", "Gojo", "Denji", "Sailor Moon",
    "Doctor Fate", "Detective Marciano", "Hombre Halcón", "Átomo",
    "Plastic Man", "Booster Gold", "Blue Beetle", "Question",
    "Hombre Máquina", "Nick Furia", "Capitán Britania", "Ms. Marvel",
    "Estrella de Fuego", "Tigra", "Metamorfo", "Deadman",
    "La Sombra", "Fantasma del Espacio", "Ave Negra", "Flecha Verde",
  ],
};

export const place = {
  1: [
    "playa", "montaña", "bosque", "desierto", "isla", "ciudad", "pueblo",
    "granja", "casa", "colegio", "hospital", "iglesia", "castillo",
    "parque", "zoo", "circo", "cine", "teatro", "museo", "biblioteca",
    "restaurante", "bar", "tienda", "supermercado", "gimnasio", "piscina",
    "estadio", "aeropuerto", "puerto", "estación", "cárcel", "banco",
    "hotel", "camping", "río", "lago", "mar", "cueva", "volcán", "selva",
  ],
  2: [
    "faro", "molino", "acantilado", "cascada", "glaciar", "duna", "oasis",
    "pantano", "arrecife", "géiser", "cañón", "laguna", "embalse", "presa",
    "acueducto", "viaducto", "túnel", "mirador", "rotonda", "peaje",
    "área de servicio", "gasolinera", "aparcamiento", "andén", "vestíbulo",
    "quirófano", "vestuario", "trastero", "buhardilla", "sótano",
    "invernadero", "lavandería", "cementerio", "catedral", "monasterio",
    "mezquita", "sinagoga", "templo", "pagoda", "ruinas",
  ],
  3: [
    "Torre Eiffel", "Taj Mahal", "Stonehenge", "Machu Picchu",
    "Muralla China", "Coliseo", "Sagrada Familia", "Cristo Redentor",
    "Torre de Pisa", "Monte Rushmore", "Petra", "Chichén Itzá",
    "Partenón", "Golden Gate", "Big Ben", "Estatua de la Libertad",
    "Gran Cañón", "Everest", "Cataratas del Niágara", "Alhambra",
    "Acueducto de Segovia", "Camino de Santiago", "Times Square",
    "Broadway", "Hollywood", "Las Vegas", "Venecia", "Santorini",
    "Praga", "Estambul", "Marrakech", "Kioto", "Angkor Wat", "Borobudur",
  ],
  4: [
    "fiordo", "istmo", "meseta", "delta", "atolón", "manglar", "tundra",
    "taiga", "estepa", "salina", "marisma", "morrena", "caldera",
    "dique seco", "esclusa", "catacumbas", "cripta", "mausoleo",
    "necrópolis", "zigurat", "anfiteatro", "hipódromo", "circo romano",
    "termas", "foro romano", "ágora", "acrópolis", "basílica", "claustro",
    "scriptorium", "refectorio", "ábside", "transepto", "arbotante",
    "campanario", "atrio",
  ],
  5: [
    "Área 51", "Chernóbil", "Prípiat", "Fukushima", "Isla de Pascua",
    "Líneas de Nazca", "Uluru", "Desierto de Atacama", "Salar de Uyuni",
    "Mar Muerto", "Mar de Aral", "Lago Baikal", "Fosa de las Marianas",
    "Dorsal mesoatlántica", "Cinturón de Fuego", "Antártida", "Svalbard",
    "Bóveda global de semillas", "Paso del Noroeste", "Estrecho de Bering",
    "Canal de Suez", "Canal de Panamá", "Cabo de Hornos",
    "Torre de Babel", "Jardines Colgantes de Babilonia",
    "Faro de Alejandría", "Coloso de Rodas", "Mausoleo de Halicarnaso",
    "Biblioteca de Alejandría", "Valle de los Reyes", "Monte Olimpo",
    "Islas Galápagos",
  ],
};
