// src/utils/CategoryWords.js


// Importación de iconos para categorías
import { FaPeopleArrows, FaUser, FaCube, FaRunning, FaStar, FaFilm, FaCrown, FaBug, FaUtensils, FaDog, FaBriefcase, FaGuitar, FaMusic, FaGamepad, FaGlobe, FaMobileAlt, FaAppleAlt, FaSuperpowers, FaMapMarkerAlt } from 'react-icons/fa';

export const CATEGORIES = [
  { key: 'all', label: 'Todos juegan', color: '#fbbf24', icon: FaPeopleArrows  },
  { key: 'person', label: 'Persona, animal o lugar', color: '#ef4444', icon: FaUser },
  { key: 'object', label: 'Objeto', color: '#3b82f6', icon: FaCube },
  { key: 'action', label: 'Acción', color: '#10b981', icon: FaRunning },
  { key: 'difficulty', label: 'Dificultad', color: '#ec4899', icon: FaStar },
  { key: 'movies', label: 'Películas o series', color: '#8b5cf6', icon: FaFilm },
  { key: 'famous', label: 'Famosos', color: '#fb923c', icon: FaCrown },
  { key: 'insect', label: 'Insectos', color: '#84cc16', icon: FaBug },
  { key: 'food', label: 'Comida y bebida', color: '#eab308', icon: FaUtensils },
  { key: 'animal', label: 'Animales', color: '#0ea5e9', icon: FaDog },
  { key: 'occupation', label: 'Profesión', color: '#6366f1', icon: FaBriefcase },
  { key: 'musicalInstrument', label: 'Instrumentos musicales', color: '#14b8a6', icon: FaGuitar },
  { key: 'song', label: 'Canciones', color: '#db2777', icon: FaMusic },
  { key: 'game', label: 'Juegos', color: '#22c55e', icon: FaGamepad },
  { key: 'country', label: 'Países', color: '#2563eb', icon: FaGlobe },
  { key: 'app', label: 'Apps o sitios web', color: '#f43f5e', icon: FaMobileAlt },
  { key: 'brand', label: 'Marcas', color: '#d97706', icon: FaAppleAlt },
  { key: 'heroe', label: 'Superhéroes', color: '#7c3aed', icon: FaSuperpowers },
  { key: 'place', label: 'Lugares', color: '#06b6d4', icon: FaMapMarkerAlt },
];


export const CATEGORY_COLORS = Object.fromEntries(CATEGORIES.map(cat => [cat.key, cat.color]));

export const CATEGORY_WORDS = {
    all: [
        "estrella", "avión", "canguro", "tormenta", "isla", "castillo", "jirafa", "espaguetis",
        "volcán", "robot", "pirámide", "microscopio", "telaraña", "escalera", "mariposa", "nave espacial",
        "reloj de arena", "globo terráqueo", "aurora", "zorro", "lago", "iglu", "escorpión", "tren",
        "trampolín", "bicicleta", "puente", "barril", "meteorito", "murciélago", "catedral", "medusa",
        "nube", "pantano", "caracol", "camaleón", "anfiteatro", "submarino", "araña", "ventana",
        "faro", "piano", "jabalí", "cactus", "monzón", "kiosco", "hámster", "saxofón", "cueva",
        "bumerán", "túnel", "abeja", "orquesta", "linterna", "templo", "cohete", "pez espada", "bufanda",
        "montaña rusa", "globo", "plaza", "esfinge", "balanza", "lagarto", "tiburón", "peonza", "furgoneta",
        "payaso", "balsa", "arco iris", "serpiente", "canoa", "parque", "paracaídas", "alfombra",
        "góndola", "vampiro", "gramófono", "máquina de escribir", "dragón", "cementerio", "cocodrilo",
        "telescopio", "tiovivo", "panal", "momia", "caravana", "gaviota", "gladiador", "fábrica",
        "cometa", "pirata", "bastón", "marioneta", "obelisco", "tienda de campaña", "monje", "catedral",
        "llama", "ballet", "espejo", "guitarra", "traje espacial", "remolino", "muralla", "domador",
        "pozo", "brújula", "caracol", "noria", "estrella fugaz", "gladiador", "cebra", "bodega",
        "cañón", "pirámide", "camello", "linterna", "caballo", "castor", "bufón", "tren", "puerto",
        "torre", "avalancha", "robot", "globos", "león", "teléfono", "máquina de coser", "monumento",
        "aeropuerto", "hospital", "escultura", "pradera", "meteorología", "circuito", "cerro", "escudo",
        "laberinto", "fortaleza", "esqueleto", "mar", "ancla", "bosque", "batería", "trueno", "muralla",
        "globo aerostático", "mural", "zoológico", "silla de ruedas", "almohada", "huracán", "lámpara",
        "moto", "bicicleta", "autobús", "pirámide", "conejo", "tigre", "caparazón", "coche de policía",
        "bombero", "aviador", "cúpula", "bodega", "escalador", "tobogán", "papiro", "librería", "candelabro",
        "kiosco", "reptil", "loro", "mapache", "calabaza", "trineo", "buey", "escondite", "canoa",
        "pelícano", "farol", "teatro", "abeto", "salto con pértiga", "tienda de campaña", "buzón",
        "juego de ajedrez", "farero", "avión de papel", "papalote", "circuito de carreras", "piragüista",
        "maratón", "bicicleta de montaña", "zapatillas", "remolque", "parque de atracciones", "surfista",
        "esnórquel", "bufanda", "ladrón", "carpeta", "mapa", "hojas", "parapente", "luna llena", "diploma",
        "guardería", "bambú", "paseo marítimo", "puerta giratoria", "monociclo", "mariposa nocturna", "caja fuerte",
        "taburete", "globo de nieve", "candelabro", "lámpara de araña", "cascada", "nido", "pasto",
        "hipopótamo", "cápsula", "pararrayos", "pasarela", "estatua", "periscopio", "flamenco", "recolector",
        "torre de reloj", "pergamino", "rosal", "brocha", "aspiradora", "patineta", "cigüeña", "serrucho",
        "yate", "monstruo", "alicate", "trinquete", "escarabajo", "ratón de biblioteca", "sable", "tobogán",
        "peonza", "viga", "ventilador", "reloj de péndulo", "frontera", "piedra lunar", "góndola", "salón de baile",
        "cañón de agua", "cosechadora", "excavadora", "caravana", "linterna de papel", "trompeta", "flautista",
        "patinaje sobre hielo", "fuente", "estanque", "juguete", "pecera", "alcázar", "microondas", "gramófono",
        "alfarería", "gaviota", "termómetro", "aljibe", "barranco", "bodega de vino", "carro de helados", "carrito de golf",
        "capilla", "tiovivo", "tractor", "torno", "grúa", "cosechadora", "manillar", "mezquita", "pozo artesiano",
        "puente colgante", "compás", "tabique", "maratón", "tapiz", "cosmódromo", "parcela", "eco", "jardín zen",
        "llavero", "abanico", "muñeca", "granada", "gladiador", "camello", "murciélago", "carroza", "murmullo",
        "muralla china", "pérgola", "mosaico", "canica", "cerrojo", "bate", "surtidor", "moho", "candelero",
        "baúl", "matraz", "abrelatas", "farola", "cinta métrica", "rejilla", "caseta", "caimán", "limonero",
        "zapato de tacón", "estuche", "trofeo", "planeta", "sastrería", "molino", "caracol", "cetro", "monasterio",
        "cangrejo", "comedor", "patrulla", "lavabo", "antorcha", "cuerda de saltar", "alfiler", "cámara submarina",
        "parque natural", "tienda de campaña", "aurora boreal", "espantapájaros", "pesebre", "fuente de chocolate",
        "pantalla", "binoculares", "maceta", "bastidor", "canoa", "foca", "tabla periódica", "cabina telefónica",
        "mapa estelar", "carro de mercado", "jeringuilla", "jabalina", "tarima", "taburete", "varita mágica", "prisma",
        "lente de aumento", "tienda de campaña", "navaja suiza", "obelisco", "trinchera", "ladrillo", "alcachofa",
        "banderín", "motocicleta", "escalera de cuerda", "regadera", "telón", "peluca", "pirata", "túnel de viento",
        "quitanieves", "carroza", "bote de remos", "saxofón", "bigote postizo", "triciclo", "papel reciclado", "farolillo",
        "caracola", "caña de pescar", "flauta dulce", "paleta de pintor", "anteojos", "periscopio", "globo terráqueo",
        "cometa", "polvo de estrellas", "cartografía", "mantarraya", "coral", "jaula", "motosierra", "pértiga"
    ],

    person: [
        "mago", "bombero", "científico", "bailarín", "astronauta", "pintor", "piloto", "vendedor",
        "profesor", "mecánico", "chef", "jugador de fútbol", "actor", "enfermero", "detective", "pirata",
        "rey", "abogado", "sacerdote", "escultor", "músico", "payaso", "soldado", "esquiador", "navegante",
        "fotógrafo", "zoologo", "presentador", "cartero", "guía turístico", "guardabosques", "veterinario",
        "ingeniero", "programador", "escritor", "pescador", "jardinero", "vendedor de globos", "barrendero",
        "capitán", "alcalde", "policía", "héroe", "villano", "profeta", "maestro de ceremonias", "luchador de sumo",
        "arquitecto", "cazador", "artista", "domador", "museo", "teatro", "aeropuerto", "montaña", "bosque",
        "playa", "ciudad", "aldea", "desierto", "universidad", "mercado", "iglesia", "castillo", "puerto",
        "granja", "templo", "biblioteca", "parque", "isla", "cueva", "acuario", "circo", "hospital", "torre",
        "palacio", "estadio", "zoológico", "fábrica", "base espacial", "cabaña", "pista de patinaje", "anfiteatro",
        "espejo de agua", "parque de diversiones", "centro comercial", "cárcel", "monasterio", "puente",
        "catedral", "plaza", "farol", "globo terráqueo", "tren", "autobús", "tractor", "carro", "barco",
        "submarino", "avión", "bicicleta", "moto", "triciclo", "velero", "góndola", "canoa", "balsa", "globo",
        "catamarán", "furgoneta", "bote", "yate", "coche de policía", "carro de bomberos", "ambulancia", "patineta",
        "scooter", "tienda de campaña", "cabaña de troncos", "molino", "granero", "tienda de comestibles", "faro",
        "mirador", "dársena", "almacén", "motel", "posada", "lavandería", "peluquería", "bar", "restaurante",
        "cafetería", "banco", "oficina de correos", "tienda de antigüedades", "taller", "gimnasio", "spa", "sauna",
        "cementerio", "invernadero", "piscina", "río", "laguna", "lago", "estanque", "catarata", "volcán", "cueva",
        "acantilado", "isla desierta", "glaciar", "caverna", "jungla", "pantano", "estepa", "sabana", "valle",
        "meseta", "catarata", "pico", "fiordo", "desfiladero", "monte", "torre de vigilancia", "cuartel", "sala de conciertos",
        "teatro de ópera", "casa de cultura", "galería de arte", "salón de baile", "discoteca", "escalera", "ascensor",
        "puerta giratoria", "alfombra roja", "ventilador", "paraguas", "sombrilla", "linterna", "faro", "silla",
        "mesa", "cama", "escritorio", "armario", "estantería", "cómoda", "perchero", "espejo", "lámpara", "reloj",
        "piano", "guitarra", "batería", "trompeta", "flauta", "arpa", "violín", "tambores", "bongó", "maracas",
        "caja de música", "gramófono", "grabadora", "microscopio", "prismáticos", "telescopio", "parlantes", "robot",
        "bicicleta de ejercicio", "cinta de correr", "pesas", "máquina de remo", "reloj de arena", "botella de agua",
        "termo", "jarrón", "plato", "cuchara", "tenedor", "cuchillo", "olla", "sartén", "tetera", "colador",
        "cazuela", "taza", "vaso", "botella", "termo", "florero", "maceta", "regadera", "pala", "rastrillo",
        "carretilla", "manguera", "escalera de mano", "tijeras de podar", "azadón", "pico", "martillo", "destornillador",
        "taladro", "sierra", "lija", "alicate", "nivel de burbuja", "cinta métrica", "brújula", "mapa", "globo",
        "diario", "revista", "cómic", "cuaderno", "libro", "diccionario", "enciclopedia", "computadora", "impresora",
        "ratón", "teclado", "pantalla", "proyector", "micrófono", "audífonos", "celular", "teléfono", "altavoz",
        "televisor", "cámara", "lupa", "tarjeta de crédito", "cartera", "pasaporte", "mochila", "maleta", "bolso",
        "billetera", "estuche", "lapicero", "lápiz", "marcador", "plumón", "crayón", "borrador", "sacapuntas",
        "tijeras", "pegamento", "grapadora", "goma elástica", "clip", "cuadro", "poster", "escultura", "estatua",
        "fuente", "obelisco", "monumento", "torre", "columna", "arco", "puerta monumental", "mosaico", "fresco",
        "murales", "pintura", "galería", "artesanía", "telares", "alfombra", "tapiz", "florero", "cuenco", "joyero",
        "cajón", "bandeja", "cofre", "carroza", "bicicleta", "patines", "barco", "scooter", "moto", "tractor",
        "profesor", "médico", "enfermero", "ingeniero", "arquitecto", "chef", "pintor",
        "carpintero", "electricista", "plomero", "mecánico", "bombero", "policía", "piloto",
        "azafata", "abogado", "juez", "escritor", "periodista", "fotógrafo", "actor", "actriz",
        "músico", "cantante", "bailarín", "deportista", "entrenador", "veterinario", "científico",
        "astronauta", "programador", "estilista", "maestro", "niñera", "jardinero", "bibliotecario",
        "alcalde", "presidente", "rey", "reina", "príncipe", "princesa", "cazador", "pescador",
        "marinero", "navegante", "guardabosques", "arqueólogo", "historiador", "pintor de brocha gorda",
        "escultor", "peluquero", "barbero", "panadero", "pastelero", "camarero", "mesero",
        "repartidor", "chofer", "taxista", "actor de doblaje", "profesor de música", "director de cine",
        "productor", "investigador", "analista", "traductor", "intérprete", "consultor", "embajador",
        "secretario", "recepcionista", "asistente", "guardia de seguridad", "soldado", "general",
        "capitán", "cadete", "sargento", "juez de paz", "piloto de helicóptero", "terapeuta", "psicólogo",
        "psiquiatra", "dentista", "ortodoncista", "dermatólogo", "cardiólogo", "cirujano", "pediatra",
        "geriatra", "partera", "ayudante", "voluntario", "coordinador", "animador", "magistrado",
        "monje", "sacerdote", "pastor", "imán", "rabino", "monja", "corredor", "cazador de tormentas",
        "explorador", "instructor de yoga", "esquiador", "surfista", "paracaidista", "alpinista",
        "montañista", "zoologista", "entomólogo", "ecologista", "ambientalista", "activista", "candidato",
        "abogado de defensa", "fiscal", "artista gráfico", "pintor al óleo", "astrónomo", "matemático",
        "físico", "químico", "biólogo", "sociólogo", "antropólogo", "economista", "filósofo", "teólogo",
        "poeta", "crítico", "editor", "curador de museo", "conservador", "arqueólogo subacuático",
        "investigador privado", "detective", "policía forense", "comisario", "embalsamador", "entrenador personal",
        "nutricionista", "consultor financiero", "administrador de redes", "especialista en TI", "diseñador de interiores",
        "agente de viajes", "gerente de hotel", "conserje", "guardaparques", "agricultor", "ganadero", "apicultor",
        "viticultor", "floricultor", "horticultor", "paisajista", "empresario", "comerciante", "artesano", "ebanista",
        "herrero", "joyero", "relojería", "vidriero", "ceramista", "alfarero", "soplador de vidrio", "orfebre",
        "cerrajero", "empacador", "operador de maquinaria", "minero", "geólogo", "topógrafo", "meteorólogo",
        "físico nuclear", "robotista", "ingeniero químico", "ingeniero de software", "ingeniero civil", "ingeniero eléctrico",
        "ingeniero mecánico", "ingeniero de sonido", "ingeniero de telecomunicaciones", "ingeniero aeronáutico",
        "capitán de barco", "contratista", "ciclista", "motociclista", "automovilista", "velocista", "nadador",
        "triatleta", "gimnasta", "tenista", "futbolista", "basquetbolista", "voleibolista", "jugador de rugby",
        "jugador de hockey", "esgrimista", "luchador", "boxeador", "judoka", "karateka", "practicante de taekwondo",
        "espadachín", "tirador", "arquero", "jinete", "amazona", "entrenador de caballos", "adiestrador de perros",
        "titiritero", "mago", "ilusionista", "payaso", "ventrílocuo", "malabarista", "trapecista", "domador de leones",
        "cuidador de zoológico", "domador de serpientes", "falconero", "entrenador de aves", "cetrero", "cuidador de animales",
        "vendedor ambulante", "feriante", "artista callejero", "caricaturista", "bufón", "humorista", "comediante",
        "locutor", "anfitrión", "presentador", "moderador", "orador", "conferenciante", "maestro de ceremonias",
        "embajador cultural", "embajador de buena voluntad", "consejero", "psicoterapeuta", "coach de vida", "orientador",
        "tutor", "coordinador de eventos", "planificador de bodas", "diseñador de moda", "modelador 3D", "animador digital",
        "animador de videojuegos", "streamer", "youtuber", "blogger", "influencer", "redactor de contenido", "fotoperiodista",
        "corresponsal", "reportero de noticias", "editor de vídeo", "productor de cine", "diseñador de vestuario", "maquillador",
        "tatuador", "piercer", "guía turístico", "fotógrafo de paisajes", "viajero", "mochilero", "explorador urbano", "pescador deportivo",
        "niño", "adolescente", "adulto", "anciano", "vecino", "huésped", "visitante", "extranjero", "turista", "invitado",
        "mascota", "gato", "perro", "canario", "hamster", "conejo", "tortuga", "pez", "loro", "cobaya", "hurón",
        "lagarto", "serpiente", "iguana", "ratón", "rata", "erizo", "camaleón", "salamandra", "zorro", "lobo", "ciervo",
        "oso", "león", "tigre", "pantera", "guepardo", "jirafa", "elefante", "rinoceronte", "hipopótamo", "canguro",
        "koala", "panda", "delfín", "ballena", "foca", "pingüino", "pelícano", "flamenco", "águila", "halcón", "búho",
        "cigüeña", "pato", "ganso", "cisne", "cuervo", "paloma", "golondrina", "gorrión", "zorzal", "petirrojo", "picaflor",
        "colibrí", "mariposa", "abeja", "avispa", "hormiga", "catarina", "escarabajo", "saltamontes", "grillo", "mantis",
        "escorpión", "araña", "cangrejo", "langosta", "pulpo", "calamar", "tiburón", "raya", "medusa", "estrella de mar",
        "caballito de mar", "erizo de mar", "coral", "caracol", "babosa", "almeja", "ostra", "cocodrilo", "caimán", "tucán",
        "gorila", "orangután", "chimpancé", "mono", "babún", "lemur", "mapache", "zorrillo", "tejón", "comadreja"
    ],


    object: [
        "lápiz", "bolígrafo", "marcador", "pluma", "borrador", "sacapuntas", "regla", "compás",
        "escuadra", "cuaderno", "libro", "agenda", "carpeta", "portafolio", "mochila", "maleta",
        "estuche", "grapadora", "clip", "tijeras", "pegamento", "cinta adhesiva", "grapas",
        "calculadora", "computadora", "teclado", "ratón", "pantalla", "monitor", "impresora",
        "teléfono", "celular", "audífonos", "altavoz", "micrófono", "cámara", "televisor",
        "control remoto", "reloj", "reloj de pulsera", "reloj de pared", "reloj de arena", "brújula",
        "mapa", "globo terráqueo", "linterna", "batería", "cargador", "cable", "enchufe", "adaptador",
        "paraguas", "sombrilla", "lupa", "prismáticos", "telescopio", "microscopio", "jarrón",
        "florero", "maceta", "planta", "regadera", "manguera", "pala", "rastrillo", "carretilla",
        "escalera", "martillo", "destornillador", "taladro", "sierra", "alicate", "llave inglesa",
        "cinta métrica", "nivel de burbuja", "serrucho", "lija", "cepillo", "brocha", "pincel",
        "paleta de pintor", "rodillo", "esmalte", "cubo", "esponja", "jabón", "champú", "toalla",
        "cepillo de dientes", "pasta de dientes", "hilo dental", "peine", "cepillo de pelo",
        "secador de pelo", "plancha", "pinza para el pelo", "espejo", "rasuradora", "maquinilla",
        "desodorante", "perfume", "loción", "crema", "sombrero", "gorro", "bufanda", "guantes",
        "botas", "zapatillas", "zapatos", "sandalias", "chanclas", "camisa", "blusa", "chaqueta",
        "abrigo", "chaleco", "pantalones", "falda", "vestido", "corbata", "cinturón", "calcetines",
        "medias", "pijama", "bata", "traje", "uniforme", "moño", "lazo", "gafas", "lentes de sol",
        "máscara", "antifaz", "casco", "collar", "pulsera", "anillo", "pendientes", "aretes",
        "reloj de bolsillo", "broche", "pasador", "gemelos", "alhajero", "cofre", "joyero", "cajón",
        "cómoda", "armario", "mesa", "silla", "taburete", "sofá", "sillón", "mecedora", "cama",
        "colchón", "almohada", "funda", "manta", "sábana", "edredón", "cobija", "cuna", "lámpara",
        "lámpara de pie", "candelabro", "pantalla de lámpara", "ventilador", "radiador", "calefactor",
        "aire acondicionado", "termostato", "refrigerador", "congelador", "microondas", "horno",
        "tostadora", "batidora", "licuadora", "cafetera", "tetera", "olla", "cazuela", "sartén",
        "cuchara", "tenedor", "cuchillo", "espátula", "colador", "rallador", "tabla de cortar",
        "abrelatas", "sacacorchos", "cucharón", "cuchillo de pan", "cuchillo de chef", "pinzas",
        "espumadera", "copa", "vaso", "taza", "plato", "bandeja", "fuente", "tazón", "juguera",
        "termo", "botella", "botella de agua", "tapón", "lata", "tarro", "caja", "bote", "contenedor",
        "basurero", "papelera", "escoba", "recogedor", "mopa", "cubeta", "trapeador", "aspiradora",
        "robot aspirador", "lavadora", "secadora", "plancha de ropa", "tabla de planchar", "perchero",
        "gancho", "colgador", "porta sombrillas", "baúl", "maletín", "carrito de compras", "bandeja de entrada",
        "archivador", "puerta", "ventana", "persiana", "cortina", "cerradura", "llave", "manilla", "picaporte",
        "interruptor", "enchufe múltiple", "luz nocturna", "bombilla", "foco", "farol", "campana", "alarma",
        "silbato", "timbre", "campanilla", "pito", "bocina", "megáfono", "altavoz portátil", "bocadillo inflable",
        "carrete de hilo", "agujas", "tijeras de costura", "alfiletero", "dedal", "hilo", "madeja", "tela",
        "retazo", "parche", "bolso", "mochila", "cartuchera", "monedero", "billetera", "funda de móvil",
        "bandeja de hielo", "molde para hornear", "bolsa de plástico", "papel de regalo", "papel aluminio",
        "película transparente", "cortapapeles", "sello", "marcador permanente", "tarjeta", "postal", "sobre",
        "carta", "invitación", "pegatina", "tarjeta de cumpleaños", "notebook", "tableta", "consola de videojuegos",
        "mando", "joystick", "tarjeta de memoria", "disco duro", "usb", "lápiz óptico", "cámara web", "trípode",
        "foco de estudio", "microscopio", "proyector", "pantalla de proyección", "filtro de luz", "pizarra blanca",
        "marcadores de pizarra", "borrador de pizarra", "estante", "repisa", "mueble de televisión", "aparador",
        "vitrina", "armario de cocina", "banco de herramientas", "cajonera", "espejo de pie", "toallero", "perchero de pie"
    ]
    ,

    action: [
        "correr", "saltar", "nadar", "bailar", "caminar", "trepar", "luchar", "volar",
        "esquiar", "patinar", "andar", "gatear", "lanzar", "patear", "golpear", "empujar",
        "tirar", "levantar", "agacharse", "saltar la cuerda", "rodar", "deslizarse", "rebotar",
        "atrapar", "perseguir", "huir", "escalar", "sumergirse", "navegar", "remar", "saltar en paracaídas",
        "bucear", "esquivar", "boxear", "luchar", "golpear con el codo", "patinar sobre hielo", "pedalear",
        "subir escaleras", "bajar escaleras", "patinar en línea", "hacer flexiones", "hacer sentadillas",
        "saltar obstáculos", "remar", "tirarse en tirolesa", "acampar", "escribir", "leer", "dibujar",
        "pintar", "esculpir", "tejer", "cortar", "pegar", "coser", "bordar", "clavar", "atornillar",
        "limpiar", "barrer", "fregar", "trapeador", "sacudir", "ordenar", "lavar", "planchar", "doblar ropa",
        "regar", "podar", "jardinear", "cocinar", "freír", "asar", "hornear", "rebanar", "pelar", "revolver",
        "batir", "mezclar", "decorar", "degustar", "sazonar", "marinar", "hervir", "enfriar", "congelar",
        "descongelar", "tostar", "preparar", "comer", "beber", "masticar", "tragar", "sorber", "saborear",
        "dormir", "soñar", "roncar", "despertar", "levantarse", "sentarse", "acostarse", "saltar de la cama",
        "dormitar", "descansar", "relajarse", "meditar", "respirar", "concentrarse", "pensar", "analizar",
        "recordar", "olvidar", "imaginar", "crear", "inventar", "planear", "organizar", "calcular", "sumar",
        "restar", "multiplicar", "dividir", "escribir a máquina", "dictar", "programar", "dibujar planos",
        "caligrafiar", "tomar notas", "leer en voz alta", "recitar", "narrar", "cantar", "tocar un instrumento",
        "afinar", "silbar", "tararear", "improvisar", "actuar", "ensayar", "aplaudir", "festejar", "brindar",
        "celebrar", "bailar salsa", "bailar tango", "zambullirse", "tomar el sol", "jugar", "competir",
        "participar", "ganar", "perder", "empatizar", "conversar", "charlar", "escuchar", "preguntar", "responder",
        "enseñar", "aprender", "estudiar", "explicar", "traducir", "interpretar", "enseñar a leer", "educar",
        "viajar", "explorar", "descubrir", "navegar en barco", "volar en avión", "hacer maletas", "desempacar",
        "acampar", "hacer senderismo", "montar a caballo", "surfear", "navegar en kayak", "pescar", "cazar",
        "fotografiar", "filmar", "editar", "subir contenido", "transmitir", "descargar", "subir archivos", "escanear",
        "imprimir", "fotocopiar", "organizar reuniones", "coordinar", "supervisar", "liderar", "delegar",
        "inspirar", "motivar", "convencer", "negociar", "discutir", "mediar", "conciliar", "firmar",
        "sellar", "aprobar", "rechazar", "aceptar", "proponer", "presentar", "preparar un informe", "disertar",
        "conferenciar", "comentar", "publicar", "redactar", "revisar", "corregir", "gritar", "susurrar",
        "reír", "llorar", "gritar de alegría", "aplaudir con entusiasmo", "susurrar un secreto", "aclamar",
        "exclamar", "quejarse", "refunfuñar", "protestar", "apaciguar", "tranquilizar", "persuadir", "asustar",
        "sorprender", "bromear", "contar chistes", "hacer reír", "hacer llorar", "emocionar", "aburrir",
        "desanimar", "despedir", "saludar", "despedirse", "abrazar", "dar la mano", "chocar los cinco", "palmear",
        "empujar suavemente", "acariciar", "besar", "dar un beso en la mejilla", "apretar", "pellizcar", "acariciar el cabello",
        "hacer cosquillas", "asustarse", "calmarse", "relajarse", "estirarse", "bocear", "desperezarse", "pestañear",
        "guiñar un ojo", "sonreír", "hacer pucheros", "hacer muecas", "poner caras", "fruncir el ceño", "levantar una ceja",
        "gesticular", "asentir", "negar con la cabeza", "cruzar los brazos", "encogerse de hombros", "dar la vuelta",
        "girar", "inclinarse", "ponerse de pie", "sentarse de golpe", "arrojar", "dar una patada", "saltar sobre un pie",
        "dar volteretas", "hacer el pino", "saltar la cuerda", "hacer piruetas", "saltar a la comba", "balancearse",
        "balancear los brazos", "hacer ejercicio", "entrenar", "hacer yoga", "hacer pilates", "hacer tai chi", "boxear",
        "practicar artes marciales", "jugar al fútbol", "jugar al tenis", "jugar al baloncesto", "jugar al voleibol", "rematar",
        "golpear con el puño", "dar un codazo", "correr una maratón", "sprintar", "trotar", "hacer bicicleta", "escalar rocas"
    ]
    ,

    difficulty: [
        "destino", "utopía", "misterio", "suspenso", "soledad", "éxtasis", "arrogancia", "miedo",
        "duda", "esperanza", "traición", "serenidad", "pasión", "introspección", "inteligencia",
        "curiosidad", "pérdida", "ambición", "compasión", "orgullo", "libertad", "paz", "guerra",
        "confusión", "recuerdo", "melancolía", "nostalgia", "perseverancia", "admiración", "cautela",
        "resiliencia", "equilibrio", "justicia", "venganza", "inocencia", "sabiduría", "tentación",
        "claridad", "oscuridad", "infinito", "progreso", "retroceso", "armonía", "desesperanza",
        "decepción", "redención", "gratitud", "simpatía", "tolerancia", "ignorancia", "desdicha",
        "euforia", "desolación", "epifanía", "conformidad", "desafío", "sacrificio", "creatividad",
        "abundancia", "vacío", "percepción", "intuición", "conciencia", "subconsciente", "paradoja",
        "revelación", "apariencia", "ideal", "contradicción", "felicidad", "tristeza", "misericordia",
        "tentación", "paradigma", "caos", "orden", "reciprocidad", "dualidad", "moralidad", "ética",
        "virtud", "pecado", "culpa", "remordimiento", "identidad", "transformación", "purificación",
        "esperanza", "desafío", "superación", "soledad", "compañerismo", "sueño", "realidad", "espejismo",
        "verdad", "mentira", "inspiración", "altruismo", "escepticismo", "ambivalencia", "individualismo",
        "colectivismo", "heroísmo", "villanía", "impulso", "razón", "emoción", "empatía", "desprecio",
        "anhelo", "apatía", "apatía", "fatiga", "determinación", "constancia", "innovación", "tradición",
        "valor", "timidez", "imaginación", "visión", "ambigüedad", "autoridad", "rebelión", "conformismo",
        "vitalidad", "aletargamiento", "caída", "auge", "paradoja", "inquietud", "serenidad", "desenlace",
        "inicio", "culminación", "simbiosis", "parasito", "complicidad", "discordia", "afinidad", "antipatía",
        "irresponsabilidad", "madurez", "inmadurez", "transcendencia", "inmanencia", "adversidad", "plenitud",
        "vacuidad", "escepticismo", "convicción", "dogma", "relatividad", "absoluto", "desafío", "aplomo",
        "fuerza", "vulnerabilidad", "ocultismo", "transparencia", "mística", "terrenal", "espiritual", "pragmático",
        "utópico", "distopía", "sátira", "ironía", "sarcasmo", "optimismo", "pesimismo", "neutralidad", "compromiso",
        "alienación", "cautela", "impetuosidad", "ansiedad", "calma", "resplandor", "oscuridad", "transición",
        "expectativa", "realización", "fracaso", "triunfo", "fe", "distracción", "atención", "concentración",
        "abstracción", "simbolismo", "ritual", "costumbre", "instinto", "impulso", "delirio", "cordura", "locura",
        "sentido", "absurdo", "sofisticación", "sencillez", "enigma", "revelación", "impresión", "espectáculo",
        "cotidianidad", "extrañeza", "normalidad", "excepción", "riesgo", "seguridad", "fragilidad", "fortaleza",
        "perfección", "imperfección", "trivialidad", "profundidad", "determinación", "hesitación", "resolución",
        "conflicto", "alianza", "cooperación", "competencia", "alianza", "estrategia", "táctica", "impulsividad",
        "calculación", "fuerza", "destreza", "habilidad", "torpeza", "entusiasmo", "desgano", "admiración",
        "resentimiento", "piedad", "indiferencia", "preocupación", "alivio", "cautela", "temeridad", "certeza",
        "sospecha", "comprensión", "desconcierto", "facilidad", "complicación", "holgura", "tensión", "disponibilidad",
        "ausencia", "presencia", "alegría", "tristeza", "satisfacción", "deseo", "repulsión", "entrega", "reserva",
        "recelo", "desprendimiento", "cariño", "odio", "admiración", "conformidad", "rebeldía", "vanguardia", "tradición",
        "modernidad", "antigüedad", "futuro", "pasado", "presente", "simetría", "asimetría", "desequilibrio", "balance",
        "inevitabilidad", "accidente", "intencionalidad", "azar", "destino", "libre albedrío", "juicio", "prejuicio",
        "percepción", "distorsión", "realismo", "idealismo", "materialismo", "espiritualismo", "proporción", "desorden",
        "resolución", "ambigüedad", "facilitar", "entorpecer", "acercamiento", "alejamiento", "frustración", "cumplimiento",
        "asombro", "monotonía", "fascinación", "desprecio", "ansia", "repugnancia", "satisfacción", "disgusto", "fervor",
        "apatía", "ambición", "temor", "valentía", "temeridad", "prudencia", "irresponsabilidad", "conciencia", "autonomía",
        "dependencia", "liberación", "reclusión", "impulso", "reflexión", "elocuencia", "tartamudeo", "fluidez", "bloqueo",
        "originalidad", "cliché", "evolución", "repetición", "renovación", "decadencia", "ascenso", "caída", "flujo",
        "estancamiento", "dinamismo", "inmovilidad", "permanencia", "transitoriedad", "inmediatez", "posteridad"
    ],
    movies: [
        "Titanic", "Avatar", "El Padrino", "Forrest Gump", "La guerra de las galaxias", "Jurassic Park", "Matrix", "Harry Potter y la piedra filosofal", "Los Simpson", "Breaking Bad",
        "Juego de Tronos", "El Rey León", "Buscando a Nemo", "Stranger Things", "Friends", "Los Vengadores", "Toy Story", "Coco", "La Bella y la Bestia", "Star Trek", "Frozen", "Gladiator",
        "Indiana Jones y los cazadores del arca perdida", "Piratas del Caribe: La maldición de la Perla Negra", "Misión Imposible", "El Resplandor", "Psicosis", "El sexto sentido", "Alien",
        "Depredador", "Regreso al futuro", "Volver al futuro", "El Gran Lebowski", "Pulp Fiction", "Kill Bill", "Reservoir Dogs", "El bueno, el feo y el malo", "La vida es bella", "Amélie",
        "La La Land", "Mad Max: Furia en la carretera", "Blade Runner", "El club de la lucha", "El pianista", "La naranja mecánica", "El silencio de los corderos", "Se7en", "Los increíbles",
        "Up", "Monstruos S.A.", "Wall·E", "Ratatouille", "Buscando a Dory", "Gru, mi villano favorito", "Shrek", "La casa de papel", "Narcos", "The Crown", "Black Mirror", "House of Cards",
        "Peaky Blinders", "Dark", "Mindhunter", "Cómo conocí a vuestra madre", "The Office", "Seinfeld", "Rick y Morty", "South Park", "Dragon Ball Z", "One Piece", "Los Caballeros del Zodiaco",
        "Pokémon", "Digimon", "Neon Genesis Evangelion", "Sailor Moon", "Doraemon", "Detective Conan", "Chernobyl", "True Detective", "Fargo", "Westworld", "Avatar: La leyenda de Aang",
        "The Mandalorian", "Obi-Wan Kenobi", "Loki", "WandaVision", "Falcon y el Soldado de Invierno", "Hawkeye", "Élite", "Vis a Vis", "La casa de las flores", "Las chicas del cable",
        "El cuento de la criada", "Big Little Lies", "Euphoria", "The Handmaid's Tale", "Better Call Saul", "Ozark", "Narcos: México", "The Witcher", "House", "Grey's Anatomy",
        "Anatomía de Grey", "Doctor Who", "Stranger Things 2", "Stranger Things 3", "Stranger Things 4", "Stranger Things 5", "Black Swan", "The Irishman", "Joker", "Parasite",
        "Tu mejor amigo", "Spotlight", "12 años de esclavitud", "Birdman", "La forma del agua", "Grand Budapest Hotel", "Moonlight", "Roma", "Gravity", "Interstellar", "Inception",
        "Dunkerque", "Origen", "Matrix Reloaded", "Matrix Revolutions", "John Wick", "John Wick 2", "John Wick 3", "Madagascar", "Kung Fu Panda", "How to Train Your Dragon",
        "The Incredibles 2", "Inside Out", "Zootopia", "Moana", "Ralph el Demoledor", "Frozen 2", "Toy Story 2", "Toy Story 3", "Toy Story 4", "Cars", "Cars 2", "Cars 3", "Up",
        "Brave", "Valiente", "Los Croods", "Ice Age", "Ice Age 2", "Ice Age 3", "Ice Age 4", "Ice Age 5", "Rio", "Rio 2", "Hotel Transylvania", "Hotel Transylvania 2",
        "Hotel Transylvania 3", "Madagascar 2", "Madagascar 3", "Megamind", "Bee Movie", "Minions", "Despicable Me 2", "Despicable Me 3", "The Secret Life of Pets",
        "The Secret Life of Pets 2", "Sing", "Trolls", "Trolls 2", "Jumanji", "Jumanji: Bienvenidos a la jungla", "Jumanji: El siguiente nivel", "The Lion King 2", "The Lion King 1",
        "Harry Potter y la cámara secreta", "Harry Potter y el prisionero de Azkaban", "Harry Potter y el cáliz de fuego", "Harry Potter y la orden del Fénix",
        "Harry Potter y el misterio del príncipe", "Harry Potter y las reliquias de la muerte 1", "Harry Potter y las reliquias de la muerte 2", "El Hobbit: Un viaje inesperado",
        "El Hobbit: La desolación de Smaug", "El Hobbit: La batalla de los cinco ejércitos", "Crepúsculo", "Amanecer", "Eclipse", "Luna nueva", "Breaking Dawn 1", "Breaking Dawn 2",
        "50 sombras de Grey", "50 sombras más oscuras", "Cincuenta sombras liberadas", "La guerra del anillo", "El retorno del rey", "La comunidad del anillo", "Las dos torres",
        "El señor de los anillos", "Piratas del Caribe 2", "Piratas del Caribe 3", "Piratas del Caribe 4", "Piratas del Caribe 5", "Star Wars: El Imperio Contraataca",
        "Star Wars: El retorno del Jedi", "Star Wars: Una nueva esperanza", "Star Wars: El despertar de la fuerza", "Star Wars: Los últimos Jedi", "Star Wars: El ascenso de Skywalker",
        "Indiana Jones 2", "Indiana Jones 3", "Indiana Jones 4", "Indiana Jones 5", "Misión Imposible 2", "Misión Imposible 3", "Misión Imposible: Protocolo fantasma",
        "Misión Imposible: Nación Secreta", "Misión Imposible: Fallout", "El caballero oscuro", "El caballero oscuro: La leyenda renace", "Batman Begins", "Superman", "Superman II",
        "Superman III", "Wonder Woman", "Aquaman", "Liga de la Justicia", "Justice League", "Thor", "Thor: Ragnarok", "Thor: El mundo oscuro", "Thor: Love and Thunder",
        "Capitán América: El primer vengador", "Capitán América: El invierno rojo", "Capitán América: Civil War", "Los Vengadores: Infinity War", "Los Vengadores: Endgame",
        "Doctor Strange", "Doctor Strange in the Multiverse of Madness", "Spider-Man", "Spider-Man 2", "Spider-Man 3", "Spider-Man: Homecoming", "Spider-Man: Lejos de casa",
        "Spider-Man: No Way Home", "Ant-Man", "Ant-Man y la Avispa", "Black Panther", "Black Panther: Wakanda Forever", "Cazafantasmas", "Ghostbusters", "Jurassic Park 2",
        "Jurassic Park 3", "Jurassic World", "Jurassic World: El reino caído", "Jurassic World: Dominion", "Star Trek: La película", "Star Trek II", "Star Trek III", "Star Trek IV",
        "Star Trek V", "Star Trek VI", "Star Trek: Primer contacto", "Star Trek: Insurrección", "Star Trek: Némesis", "Guardianes de la Galaxia", "Guardianes de la Galaxia Vol. 2",
        "Guardianes de la Galaxia Vol. 3", "Thor: Amor y Trueno", "Capitana Marvel", "Shazam!", "Shazam! Fury of the Gods", "Kick-Ass", "Deadpool", "Deadpool 2", "Logan", "X-Men",
        "X-Men 2", "X-Men: La decisión final", "X-Men: Primera generación", "X-Men: Días del futuro pasado", "X-Men: Apocalipsis", "X-Men: Fénix oscura", "Wolverine", "Wolverine: Inmortal",
        "Los Cuatro Fantásticos", "Los Cuatro Fantásticos y Silver Surfer", "El Increíble Hulk", "Hulk", "Blurred"
    ],
    /* Top 100 más taquilleras
    'Avatar',
'Avengers: Endgame',
'Avatar: The Way of Water',
'Titanic',
'Ne Zha 2',
'Star Wars: Episodio VII - El despertar de la Fuerza',
'Avengers: Infinity War',
'Spider-Man: No Way Home',
'Inside Out 2',
'Jurassic World',
'El rey león',
'The Avengers',
'Furious 7',
'Top Gun: Maverick',
'Frozen II',
'Barbie',
'Avengers: Age of Ultron',
'Super Mario Bros.: la película',
'Black Panther',
'Harry Potter y las reliquias de la Muerte: parte 2',
'Deadpool & Wolverine',
'Star Wars: Episodio VIII - Los últimos Jedi',
'Jurassic World: el reino caído',
'Frozen',
'La bella y la bestia',
'Los Increíbles 2',
'The Fate of the Furious',
'Iron Man 3',
'Minions',
'El Señor de los Anillos: el retorno del Rey',
'Capitán América: Civil War',
'Aquaman',
'Skyfall',
'Spider-Man: lejos de casa',
'Capitana Marvel',
'Transformers: el lado oscuro de la luna',
'The Dark Knight Rises',
'Parque Jurásico',
'Transformers: la era de la extinción',
'Star Wars: Episodio IX - El ascenso de Skywalker',
'Joker',
'Toy Story 4',
'Toy Story 3',
'Pirates of the Caribbean: Dead Mans Chest',
'Moana 2',
'Rogue One: una historia de Star Wars',
'Aladdín',
'Pirates of the Caribbean: On Stranger Tides',
'Despicable Me 3',
'Buscando a Dory',
'Star Wars: Episodio I - La amenaza fantasma',
'Zootopia',
'Alicia en el país de las maravillas',
'Harry Potter y la piedra filosofal',
'El hobbit: un viaje inesperado',
'The Dark Knight',
'Jurassic World: Dominion',
'Jumanji: Welcome to the Jungle',
'El rey león',
'Oppenheimer',
'Lilo & Stitch',
'Harry Potter y las reliquias de la Muerte: parte 1',
'Despicable Me 2',
'Despicable Me 4',
'El libro de la selva',
'El hobbit: la batalla de los Cinco Ejércitos',
'Piratas del Caribe: en el fin del mundo',
'El hobbit: la desolación de Smaug',
'Doctor Strange en el multiverso de la locura',
'Una película de Minecraft',
'El Señor de los Anillos: las dos torres',
'Buscando a Nemo',
'Minions: The Rise of Gru',
'Harry Potter y la Orden del Fénix',
'Harry Potter y el misterio del príncipe',
'Shrek 2',
'Harry Potter y la cámara secreta',
'Bohemian Rhapsody',
'La Batalla del Lago de Changjin',
'Harry Potter y el cáliz de fuego',
'Spider-Man 3',
'Ice Age: Dawn of the Dinosaurs',
'El Señor de los Anillos: la Comunidad del Anillo',
'Spectre',
'Spider-Man: Homecoming',
'Ice Age: Continental Drift',
'The Secret Life of Pets',
'Batman v Superman: Dawn of Justice',
'El Guerrero Lobo 2',
'Star Wars: Episodio III - La venganza de los Sith',
'Los juegos del hambre: en llamas',
'Guardianes de la Galaxia vol. 2',
'Black Panther: Wakanda Forever',
'Inside Out',
'Venom',
'Thor: Ragnarok',
'The Twilight Saga: Breaking Dawn - Part 2',
'Guardianes de la Galaxia vol. 3',
'Inception',
'Transformers: la venganza de los caídos'
    */
    famous: [
        "Elon Musk", "Barack Obama", "Lionel Messi", "Cristiano Ronaldo", "Oprah Winfrey", "Taylor Swift", "Beyoncé", "Shakira", "Michael Jackson", "Madonna",
        "Bill Gates", "Jeff Bezos", "Mark Zuckerberg", "Steve Jobs", "Warren Buffett", "Rihanna", "Lady Gaga", "Adele", "Ed Sheeran", "Drake",
        "LeBron James", "Serena Williams", "Roger Federer", "Usain Bolt", "Simone Biles", "Tom Brady", "Tiger Woods", "Michael Jordan", "Diego Maradona", "Pelé",
        "Rafael Nadal", "Novak Djokovic", "Lewis Hamilton", "Valentino Rossi", "Fernando Alonso", "Roger Waters", "Paul McCartney", "John Lennon", "Freddie Mercury", "David Bowie",
        "Brad Pitt", "Angelina Jolie", "Leonardo DiCaprio", "Tom Cruise", "Will Smith", "Dwayne Johnson", "Scarlett Johansson", "Jennifer Lopez", "Robert Downey Jr.", "Johnny Depp",
        "Emma Watson", "Daniel Radcliffe", "Morgan Freeman", "Meryl Streep", "Julia Roberts", "George Clooney", "Keanu Reeves", "Jackie Chan", "Bruce Lee", "Arnold Schwarzenegger",
        "Pablo Picasso", "Salvador Dalí", "Frida Kahlo", "Vincent van Gogh", "Leonardo da Vinci", "Albert Einstein", "Isaac Newton", "Stephen Hawking", "Marie Curie", "Malala Yousafzai",
        "Nelson Mandela", "Mahatma Gandhi", "Martin Luther King", "Angela Merkel", "Vladimir Putin", "Xi Jinping", "Emmanuel Macron", "Donald Trump", "Joe Biden", "Kim Jong-un",
        "Greta Thunberg", "Papa Francisco", "Dalai Lama", "Reina Isabel II", "Principe William", "Principe Harry", "Cristina Fernández", "Shinzo Abe", "Narendra Modi", "Recep Tayyip Erdogan",
        "Ronaldo Nazário", "Zinedine Zidane", "Andrés Iniesta", "Kylian Mbappé", "Neymar Jr.", "Luis Suárez", "Karim Benzema", "Megan Rapinoe", "Marta Vieira da Silva", "Yoko Ono"
    ],
    insect: [
        "Hormiga","Abeja","Avispa","Mosquito","Mosca","Libélula","Mariposa","Polilla","Escarabajo","Mariquita","Cigarra","Saltamontes","Grillo","Cucaracha","Chinche","Pulga","Piojo",
        "Tábano","Termita","Mantis religiosa","Mosca de la fruta","Escorpión","Tijereta","Gorgojo","Carcoma","Crisopa","Alacrán cebollero","Zancudo","Mosca tse-tsé","Tricóptero",
        "Lepisma","Barrenador","Cochinilla","Ortóptero","Efímera","Caddisfly","Insecto palo","Insecto hoja","Cigarrilla","Tórsalo","Jejen","Avispón","Bicho bola","Bicho de la humedad",
        "Tarántula roja","Escarabajo rinoceronte","Luciérnaga","Ciempiés","Milpiés","Bicho canasto","Insecto escudo","Barrenador del café","Garrapata","Trips","Bicho del trigo",
        "Bicho de la col","Escarabajo del pepino","Pulgón","Langosta","Mosquito tigre","Cucaracha americana","Panalero","Bicho del arroz","Hormiga león","Bicho palo malayo",
        "Insecto del jabón","Chinche apestosa","Insecto acuático","Ciempiés doméstico","Bicho camello","Mosca verde","Mosca azul",
        "Tábano de los caballos","Escarabajo pelotero","Escarabajo ciervo","Escarabajo dorado","Escarabajo de alfombra","Tijereta común","Gorgojo del maíz","Gorgojo del arroz",
        "Hormiga roja","Hormiga negra","Mosca de la carne","Mosca del vinagre","Piojo del cuerpo","Piojo de la cabeza","Mariposa monarca","Polilla gitana","Tarántula tigre",
        "Mantis orquídea","Mantis hoja","Luciérnaga común","Escarabajo bombardero","Escarabajo de la patata","Mariposa búho","Abejorro","Cochinilla del maíz"
] ,
    food: [
        "Pan", "Arroz", "Pasta", "Patata", "Tomate", "Lechuga", "Zanahoria", "Pimiento",
        "Cebolla", "Ajo", "Aceite de oliva", "Mantequilla", "Queso", "Leche", "Yogur",
        "Huevos", "Carne de ternera", "Carne de cerdo", "Pollo", "Pescado", "Marisco",
        "Gambas", "Calamares", "Pulpo", "Mejillones", "Almejas", "Salmón", "Atún",
        "Bacalao", "Lenguado", "Sardinas", "Boquerones", "Jamón ibérico", "Chorizo",
        "Salchichón", "Morcilla", "Paté", "Tofu", "Tempeh", "Legumbres", "Lentejas",
        "Garbanzos", "Alubias", "Guisantes", "Maíz", "Guiso de lentejas", "Cocido",
        "Paella", "Fideuá", "Tortilla de patatas", "Gazpacho", "Salmorejo", "Ajoblanco",
        "Empanada", "Croquetas", "Tortilla francesa", "Pizza", "Hamburguesa", "Hot dog",
        "Sándwich", "Bocadillo", "Ensalada mixta", "Tabulé", "Cuscús", "Sushi",
        "Tempura", "Ramen", "Pho", "Curry", "Tikka masala", "Pad thai", "Dumplings",
        "Falafel", "Hummus", "Guacamole", "Nachos", "Tacos", "Burrito", "Quesadilla",
        "Chili con carne", "Brownie", "Galleta", "Bizcocho", "Tarta de queso", "Tarta de manzana",
        "Helado", "Sorbetes", "Flan", "Natillas", "Crema catalana", "Churros", "Buñuelos",
        "Magdalenas", "Croissant", "Panecillo", "Bagel", "Muffin", "Donut", "Café",
        "Té", "Chocolate caliente", "Coca‑cola", "Zumo de naranja", "Cerveza", "Vino tinto",
        "Vino blanco", "Sidra"
    ],
    animal: [
        "Perro", "Gato", "Caballo", "Vaca", "Cerdo", "Oveja", "Cabra", "Conejo",
        "Ratón", "Rata", "Hámster", "Hurón", "Cobaya", "Pájaro", "Loro", "Canario",
        "Gorrión", "Paloma", "Águila", "Halcón", "Búho", "Lechuza", "Pato", "Oca",
        "Ganso", "Gallina", "Pavo", "Codorniz", "Pez", "Tiburón", "Delfín", "Ballena",
        "Orca", "Pulpo", "Calamar", "Medusa", "Erizo de mar", "Estrella de mar",
        "Langosta", "Cangrejo", "Gamba", "Caracol", "Babosa", "Caracol de mar",
        "Ciempiés", "Milpiés", "Hormiga", "Abeja", "Avispa", "Mosca", "Mosquito",
        "Mariposa", "Polilla", "Saltamontes", "Grillo", "Escarabajo", "Cucaracha",
        "Araña", "Escorpión", "Serpiente", "Culebra", "Lagarto", "Camaleón", "Iguana",
        "Tortuga", "Galápago", "Rana", "Sapo", "Salamandra", "Trucha", "Salmón",
        "Atún", "Bacalao", "Sardina", "Lenguado", "Esturión", "Carpa", "Piraña",
        "Hipopótamo", "Rinoceronte", "Elefante", "Jirafa", "Cebra", "León", "Tigre",
        "Pantera", "Leopardo", "Cheetah", "Oso", "Lobo", "Zorro", "Mapache", "Nutria",
        "Jabalí", "Ciervo", "Corzo", "Alce", "Jirafa", "Antílope", "Búfalo",
        "Camello", "Dromedario", "Llama", "Alpaca"
    ],
    occupation: [
        "Médico", "Enfermero", "Cirujano", "Dentista", "Farmacéutico", "Veterinario",
        "Profesor", "Maestro", "Investigador", "Científico", "Ingeniero", "Arquitecto",
        "Abogado", "Juez", "Fiscal", "Notario", "Periodista", "Redactor", "Editor",
        "Bibliotecario", "Traductor", "Intérprete", "Piloto", "Azafata", "Controlador aéreo",
        "Tripulante de cabina", "Bombero", "Policía", "Guardia civil", "Soldado",
        "Marinero", "Camionero", "Taxista", "Conductor de autobús", "Cartero", "Repartidor",
        "Cocinero", "Chef", "Camarero", "Barman", "Barista", "Panadero", "Pastelero",
        "Cortador de jamón", "Carnicero", "Pescadero", "Frutero", "Verdulero",
        "Carnicero", "Herrero", "Carpintero", "Albañil", "Fontanero", "Electricista",
        "Soldador", "Pintor", "Yesista", "Tejedor", "Tapicero", "Alfarero", "Joyero",
        "Relojero", "Sastre", "Modista", "Diseñador de moda", "Fotógrafo", "Camarógrafo",
        "Actor", "Actriz", "Director de cine", "Productor", "Músico", "Cantante",
        "Batería", "Guitarrista", "Bajista", "Pianista", "Violinista", "Director de orquesta",
        "Coreógrafo", "Bailarín", "Editor de vídeo", "Desarrollador de software",
        "Diseñador gráfico", "Community manager", "Analista de datos", "Administrador de sistemas",
        "Técnico de soporte", "Psicólogo", "Trabajador social", "Economista", "Contable",
        "Auditor", "Asesor financiero", "Corredor de seguros", "Agente inmobiliario"
    ],
      musicalInstrument: [
    "Piano","Guitarra acústica","Guitarra eléctrica","Bajo","Violín",
    "Viola","Violonchelo","Contrabajo","Arpa","Clarinete","Flauta travesera",
    "Flauta dulce","Oboe","Fagot","Trompeta","Trombón","Tuba","Bombardino",
    "Corneta","Trompa","Saxofón","Órgano","Acordeón","Armónica","Ukelele","Mandolina",
    "Laúd","Banjo","Balalaika","Zanfona","Dulcimer","Clavecín","Sintetizador",
    "Theremin","Vibráfono","Xilófono","Marimba","Campanas tubulares","Gong",
    "Platillos","Redoblante","Bombo","Caja china","Timbales","Bongos","Congas",
    "Cajón","Pandero","Pandereta","Triángulo","Castañuelas","Claves","Güiro",
    "Maracas","Quijada de burro","Shakuhachi","Didgeridoo","Sitar","Tabla",
    "Djembé","Charango","Cuatro venezolano","Cuatro puertorriqueño","Tres cubano",
    "Bouzouki","Oud","Ney","Koto","Shamisen","Pipa","Guzheng","Erhu","Sarangi",
    "Santur","Tambura","Rebec","Shawm","Cornamusa","Gaita","Shofar","Udu","Mbira",
    "Balafón","Steel drum","Hang drum","Jew's harp","Glass armonica","Waterphone",
    "Ondas Martenot","Celesta","Piccolo","Contrafagot","Serpiente","Cornetto",
    "Regal","Ocarina"
  ],

  song: [
    "Imagine","Bohemian Rhapsody","Hotel California","Stairway to Heaven","Hey Jude",
    "Like a Rolling Stone","Smells Like Teen Spirit","Billie Jean","Sweet Child O' Mine",
    "Purple Rain","Let It Be","Yesterday","Thriller","I Will Always Love You",
    "My Heart Will Go On","Despacito","La Bamba","Macarena","Bailando","Aserejé",
    "Héroe","Corazón Partío","Livin' on a Prayer","Another One Bites the Dust",
    "We Are the Champions","Wonderwall","Don't Stop Believin'","Proud Mary",
    "Paint It, Black","(I Can't Get No) Satisfaction","Hallelujah","Shape of You",
    "Rolling in the Deep","Hello","Someone Like You","Uptown Funk","Happy",
    "Call Me Maybe","Royals","Bad Guy","Blinding Lights","Easy on Me","Shallow",
    "All I Want for Christmas Is You","Jingle Bells","Feliz Navidad","La Tortura",
    "Música Ligera","Corazón Espinado","Livin' la Vida Loca","Smooth","Creep",
    "Zombie","Back in Black","Thunderstruck","Highway to Hell","Nothing Else Matters",
    "Enter Sandman","One","Numb","In the End","Clocks","Viva la Vida","Paradise",
    "Firework","Teenage Dream","Umbrella","Poker Face","Bad Romance","Toxic","Just the Way You Are",
    "Grenade","Crazy in Love","Single Ladies (Put a Ring on It)","Halo","Diamonds",
    "Chandelier","Radioactive","Demons","Believer","Someone You Loved","Señorita",
    "Havana","Cheap Thrills","Rockabye","Yellow","Closer","See You Again","Girls Like You",
    "Let Her Go","Wake Me Up","Thinking Out Loud","All of Me","Perfect","God’s Plan",
    "Old Town Road","Sunflower","Levitating","Watermelon Sugar","Bad Habits"
  ],

  game: [
    "Ajedrez","Damas","Parchís","La Oca","Monopoly","Risk","Catan","Carcassonne",
    "Scrabble","Cluedo","Trivial Pursuit","Uno","Bingo","Dominó","Mahjong","Póker",
    "Blackjack","Ruleta","Backgammon","Go","Senet","Twister","Escondite","Rayuela",
    "Sillas musicales","La gallinita ciega","Escondite inglés","Saltos a la comba",
    "Pilla-pilla","Corre que te pillo","La mancha","El pañuelo","Quemados","Balón prisionero",
    "Petanca","Mus","Tute","Brisca","Chinchón","Escoba","Truco","Sueca","Cinquillo",
    "Rummy","Magic: The Gathering","Yu-Gi-Oh!","Pokémon TCG","Hearthstone","Gwent",
    "KeyForge","FIFA","Pro Evolution Soccer","Fortnite","Minecraft","League of Legends",
    "World of Warcraft","Grand Theft Auto V","The Legend of Zelda: Breath of the Wild",
    "Super Mario Bros.","Mario Kart","Tetris","Pac-Man","Space Invaders",
    "Sonic the Hedgehog","Crash Bandicoot","Spyro the Dragon","Metal Gear Solid",
    "Resident Evil","Silent Hill","Final Fantasy VII","The Witcher 3: Wild Hunt",
    "Red Dead Redemption 2","Call of Duty: Modern Warfare","Overwatch","Apex Legends",
    "Counter-Strike: Global Offensive","Dota 2","Valorant","Among Us","Fall Guys",
    "Rocket League","Stardew Valley","Animal Crossing: New Horizons","The Sims 4",
    "Civilization VI","Age of Empires II","StarCraft II","Civilization V","Cities: Skylines",
    "SimCity","Pokémon","Super Smash Bros. Ultimate","Horizon: Zero Dawn",
    "The Last of Us","God of War","Uncharted 4","Death Stranding","Sekiro: Shadows Die Twice",
    "Elden Ring","Cyberpunk 2077"
  ],
  country: [
    "España","Francia","Italia","Alemania","Reino Unido","Estados Unidos","Canadá","México","Brasil","Argentina",
    "Chile","Perú","Colombia","Venezuela","Ecuador","Bolivia","Uruguay","Paraguay","Portugal","Países Bajos",
    "Bélgica","Suiza","Austria","Rusia","China","Japón","Corea del Sur","India","Pakistán","Bangladés",
    "Indonesia","Malasia","Tailandia","Vietnam","Filipinas","Australia","Nueva Zelanda","Egipto","Sudáfrica","Nigeria",
    "Kenia","Marruecos","Argelia","Túnez","Libia","Arabia Saudí","Emiratos Árabes Unidos","Israel","Turquía","Grecia",
    "Suecia","Noruega","Dinamarca","Finlandia","Polonia","República Checa","Hungría","Rumanía","Bulgaria","Ucrania",
    "Bielorrusia","Eslovaquia","Eslovenia","Croacia","Serbia","Bosnia y Herzegovina","Montenegro","Albania","Macedonia del Norte","Kosovo",
    "Islandia","Irlanda","Escocia","Gales","Turkmenistán","Kazajistán","Uzbekistán","Irán","Iraq","Siria",
    "Líbano","Jordania","Kuwait","Omán","Yemen","Qatar","Baréin","Chipre","Malta","Luxemburgo",
    "Mónaco","Liechtenstein","Andorra","San Marino","Ciudad del Vaticano","Singapur","Brunei","Nepal","Bután","Sri Lanka",
    "Mongolia","Corea del Norte","Myanmar","Camboya","Laos","Papúa Nueva Guinea","Fiji","Samoa","Tonga","Vanuatu"
  ],

  app: [
    "WhatsApp","Facebook","Instagram","Twitter","Snapchat","TikTok","YouTube","Spotify","Netflix","Amazon",
    "eBay","AliExpress","Google Maps","Google Drive","Dropbox","Uber","Airbnb","Booking.com","Tinder","Bumble",
    "LinkedIn","Slack","Microsoft Teams","Zoom","Skype","Gmail","Outlook","Reddit","Pinterest","Tumblr",
    "Quora","Medium","WordPress","Wix","Canva","Adobe Photoshop","Adobe Illustrator","Visual Studio Code","WhatsApp Business","Telegram",
    "Signal","WeChat","Line","Viber","Discord","Twitch","Kickstarter","GoFundMe","Patreon","PayPal",
    "Venmo","Revolut","N26","ING","BBVA","Santander","CaixaBank","Bankia","Stripe","GitHub",
    "GitLab","Bitbucket","Jira","Trello","Asana","Monday.com","Notion","Evernote","Todoist","Pocket",
    "Flipboard","Shazam","SoundHound","Deezer","Apple Music","Apple TV","HBO Max","Disney+","Crunchyroll","Prime Video",
    "Hulu","BBC iPlayer","Google Photos","Google Calendar","Maps","Uber Eats","Glovo","Deliveroo","Just Eat","Cabify"
  ],

  brand: [
    "Nike","Adidas","Puma","Reebok","Under Armour","New Balance","Asics","Converse","Vans","Levi's",
    "Calvin Klein","Hugo Boss","Zara","Mango","H&M","Inditex","Massimo Dutti","Pull & Bear","Bershka","Stradivarius",
    "Oysho","Springfield","Desigual","Loewe","Balenciaga","Gucci","Prada","Louis Vuitton","Chanel","Dior",
    "Hermès","Cartier","Rolex","TAG Heuer","Omega","Breitling","Sephora","L'Oréal","Estée Lauder","Maybelline",
    "Nivea","Dove","Pantene","Head & Shoulders","Colgate","Oral-B","Gillette","Nespresso","Nestlé","Coca-Cola",
    "Pepsi","Fanta","Sprite","Red Bull","Starbucks","McDonald's","Burger King","KFC","Subway","Domino's",
    "Pizza Hut","Costa Coffee","Baskin-Robbins","Häagen-Dazs","Lipton","Twinings","Heineken","Amstel","Mahou","Cruzcampo",
    "Estrella Damm","San Miguel","Guinness","Budweiser","Corona","Absolut","Smirnoff","Johnnie Walker","Jack Daniel's","Jägermeister",
    "Bacardi","Captain Morgan","Avon","Clinique","IKEA","Carrefour","Mercadona","Lidl","Aldi","Eroski",
    "El Corte Inglés","Apple","Samsung","Sony","LG","Huawei"
  ],

  heroe: [
    "Superman","Batman","Wonder Woman","Flash","Green Lantern","Aquaman","Cyborg","Spider-Man","Iron Man","Captain America",
    "Thor","Hulk","Black Widow","Hawkeye","Doctor Strange","Black Panther","Ant-Man","Wasp","Captain Marvel","Scarlet Witch",
    "Vision","Falcon","Winter Soldier","Star-Lord","Gamora","Drax","Rocket Raccoon","Groot","Nebula","Doctor Fate",
    "Martian Manhunter","Shazam","Batgirl","Robin","Nightwing","Daredevil","Punisher","Elektra","Luke Cage","Jessica Jones",
    "Iron Fist","Ghost Rider","Silver Surfer","Green Arrow","Black Canary","John Constantine","Hellboy","Spawn","Aquaman (Rebirth)","Power Girl",
    "Hawkman","Hawkgirl","Zatanna","Beast Boy","Cyborg (New 52)","Blue Beetle","Booster Gold","Plastic Man","Starman","Dr. Mid-Nite",
    "Green Arrow (Oliver Queen)","The Atom","Black Lightning","Firestorm","Doctor Manhattan","Vibe","Katana","Azrael","Red Hood","Mr. Miracle",
    "Mister Terrific","Oracle","Static Shock","Supergirl","Martian Manhunter (J'onn)","Miss Martian","Impulse","Cassandra Cain","Spoiler","Artemis"
  ],

  place: [
    "Museo del Prado","Sagrada Familia","Torre Eiffel","Estatua de la Libertad","Gran Muralla China","Machu Picchu","Taj Mahal","Coliseo de Roma","Pirámides de Guiza","Stonehenge",
    "Gran Cañón","Desierto del Sahara","Amazonia","Parque Nacional Yellowstone","Cataratas Victoria","Monte Everest","Monte Fuji","Monte Kilimanjaro","Antártida","Caribe",
    "Ibiza","Mallorca","Barcelona","Madrid","Sevilla","Valencia","Bilbao","Granada","Córdoba","Zaragoza",
    "Málaga","Santiago de Compostela","Toledo","Salamanca","San Sebastián","Pamplona","Burgos","León","Valladolid","Alicante",
    "Murcia","Vigo","Gijón","Las Palmas","Tenerife","Lanzarote","Fuerteventura","La Palma","El Hierro","Formentera",
    "Menorca","Costa Brava","Costa del Sol","Costa Dorada","Costa Blanca","Londres","París","Roma","Berlín","Nueva York",
    "Los Ángeles","Tokio","Pekín","Shanghái","Hong Kong","Sídney","Melbourne","Vancouver","Toronto","San Francisco",
    "Chicago","Miami","Río de Janeiro","Buenos Aires","Ciudad de México","Cancún","Dubái","Singapur","Bangkok","Seúl",
    "San Petersburgo","Moscú","Estocolmo","Oslo","Copenhague","Helsinki","Praga","Budapest","Cracovia","Dubrovnik"
  ]
};