// src/utils/CategoryWords.js

export const CATEGORY_WORDS = {
all: [
                "estrella", "avión", "canguro", "tormenta", "isla", "castillo", "jirafa", "espaguetis",
                "volcán", "robot", "pirámide", "microscopio", "telaraña", "escalera", "mariposa", "nave espacial",
                "reloj de arena", "globo terráqueo", "aurora", "zorro", "lago", "iglu", "escorpión", "tren",
                "trampolín", "bicicleta", "puente", "barril", "meteorito", "murciélago", "catedral", "medusa",
                "nube", "pantano", "caracol", "camaleón", "anfiteatro", "submarino", "araña", "ventana",
                "faro", "piano", "jabalí", "cactus", "monzón", "kiosco", "hámster", "saxofón", "cueva",
                "bumerán", "túnel", "abeja", "orquesta", "linterna", "templo", "cohete", "pez espada", "bufanda",
                "montaña rusa", "globo", "plaza", "esfinge", "balanza", "lagarto", "tiburón", "peonza", "furgoneta",
                "payaso", "balsa", "arco iris", "serpiente", "canoa", "parque", "paracaídas", "alfombra",
                "góndola", "vampiro", "gramófono", "máquina de escribir", "dragón", "cementerio", "cocodrilo",
                "telescopio", "tiovivo", "panal", "momia", "caravana", "gaviota", "gladiador", "fábrica",
                "cometa", "pirata", "bastón", "marioneta", "obelisco", "tienda de campaña", "monje", "catedral",
                "llama", "ballet", "espejo", "guitarra", "traje espacial", "remolino", "muralla", "domador",
                "pozo", "brújula", "caracol", "noria", "estrella fugaz", "gladiador", "cebra", "bodega",
                "cañón", "pirámide", "camello", "linterna", "caballo", "castor", "bufón", "tren", "puerto",
                "torre", "avalancha", "robot", "globos", "león", "teléfono", "máquina de coser", "monumento",
                "aeropuerto", "hospital", "escultura", "pradera", "meteorología", "circuito", "cerro", "escudo",
                "laberinto", "fortaleza", "esqueleto", "mar", "ancla", "bosque", "batería", "trueno", "muralla",
                "globo aerostático", "mural", "zoológico", "silla de ruedas", "almohada", "huracán", "lámpara",
                "moto", "bicicleta", "autobús", "pirámide", "conejo", "tigre", "caparazón", "coche de policía",
                "bombero", "aviador", "cúpula", "bodega", "escalador", "tobogán", "papiro", "librería", "candelabro",
                "kiosco", "reptil", "loro", "mapache", "calabaza", "trineo", "buey", "escondite", "canoa",
                "pelícano", "farol", "teatro", "abeto", "salto con pértiga", "tienda de campaña", "buzón",
                "juego de ajedrez", "farero", "avión de papel", "papalote", "circuito de carreras", "piragüista",
                "maratón", "bicicleta de montaña", "zapatillas", "remolque", "parque de atracciones", "surfista",
                "esnórquel", "bufanda", "ladrón", "carpeta", "mapa", "hojas", "parapente", "luna llena", "diploma",
                "guardería", "bambú", "paseo marítimo", "puerta giratoria", "monociclo", "mariposa nocturna", "caja fuerte",
                "taburete", "globo de nieve", "candelabro", "lámpara de araña", "cascada", "nido", "pasto",
                "hipopótamo", "cápsula", "pararrayos", "pasarela", "estatua", "periscopio", "flamenco", "recolector",
                "torre de reloj", "pergamino", "rosal", "brocha", "aspiradora", "patineta", "cigüeña", "serrucho",
                "yate", "monstruo", "alicate", "trinquete", "escarabajo", "ratón de biblioteca", "sable", "tobogán",
                "peonza", "viga", "ventilador", "reloj de péndulo", "frontera", "piedra lunar", "góndola", "salón de baile",
                "cañón de agua", "cosechadora", "excavadora", "caravana", "linterna de papel", "trompeta", "flautista",
                "patinaje sobre hielo", "fuente", "estanque", "juguete", "pecera", "alcázar", "microondas", "gramófono",
                "alfarería", "gaviota", "termómetro", "aljibe", "barranco", "bodega de vino", "carro de helados", "carrito de golf",
                "capilla", "tiovivo", "tractor", "torno", "grúa", "cosechadora", "manillar", "mezquita", "pozo artesiano",
                "puente colgante", "compás", "tabique", "maratón", "tapiz", "cosmódromo", "parcela", "eco", "jardín zen",
                "llavero", "abanico", "muñeca", "granada", "gladiador", "camello", "murciélago", "carroza", "murmullo",
                "muralla china", "pérgola", "mosaico", "canica", "cerrojo", "bate", "surtidor", "moho", "candelero",
                "baúl", "matraz", "abrelatas", "farola", "cinta métrica", "rejilla", "caseta", "caimán", "limonero",
                "zapato de tacón", "estuche", "trofeo", "planeta", "sastrería", "molino", "caracol", "cetro", "monasterio",
                "cangrejo", "comedor", "patrulla", "lavabo", "antorcha", "cuerda de saltar", "alfiler", "cámara submarina",
                "parque natural", "tienda de campaña", "aurora boreal", "espantapájaros", "pesebre", "fuente de chocolate",
                "pantalla", "binoculares", "maceta", "bastidor", "canoa", "foca", "tabla periódica", "cabina telefónica",
                "mapa estelar", "carro de mercado", "jeringuilla", "jabalina", "tarima", "taburete", "varita mágica", "prisma",
                "lente de aumento", "tienda de campaña", "navaja suiza", "obelisco", "trinchera", "ladrillo", "alcachofa",
                "banderín", "motocicleta", "escalera de cuerda", "regadera", "telón", "peluca", "pirata", "túnel de viento",
                "quitanieves", "carroza", "bote de remos", "saxofón", "bigote postizo", "triciclo", "papel reciclado", "farolillo",
                "caracola", "caña de pescar", "flauta dulce", "paleta de pintor", "anteojos", "periscopio", "globo terráqueo",
                "cometa", "polvo de estrellas", "cartografía", "mantarraya", "coral", "jaula", "motosierra", "pértiga"
            ],      
            
            person: [
                "mago", "bombero", "científico", "bailarín", "astronauta", "pintor", "piloto", "vendedor",
                "profesor", "mecánico", "chef", "jugador de fútbol", "actor", "enfermero", "detective", "pirata",
                "rey", "abogado", "sacerdote", "escultor", "músico", "payaso", "soldado", "esquiador", "navegante",
                "fotógrafo", "zoologo", "presentador", "cartero", "guía turístico", "guardabosques", "veterinario",
                "ingeniero", "programador", "escritor", "pescador", "jardinero", "vendedor de globos", "barrendero",
                "capitán", "alcalde", "policía", "héroe", "villano", "profeta", "maestro de ceremonias", "luchador de sumo",
                "arquitecto", "cazador", "artista", "domador", "museo", "teatro", "aeropuerto", "montaña", "bosque",
                "playa", "ciudad", "aldea", "desierto", "universidad", "mercado", "iglesia", "castillo", "puerto",
                "granja", "templo", "biblioteca", "parque", "isla", "cueva", "acuario", "circo", "hospital", "torre",
                "palacio", "estadio", "zoológico", "fábrica", "base espacial", "cabaña", "pista de patinaje", "anfiteatro",
                "espejo de agua", "parque de diversiones", "centro comercial", "cárcel", "monasterio", "puente",
                "catedral", "plaza", "farol", "globo terráqueo", "tren", "autobús", "tractor", "carro", "barco",
                "submarino", "avión", "bicicleta", "moto", "triciclo", "velero", "góndola", "canoa", "balsa", "globo",
                "catamarán", "furgoneta", "bote", "yate", "coche de policía", "carro de bomberos", "ambulancia", "patineta",
                "scooter", "tienda de campaña", "cabaña de troncos", "molino", "granero", "tienda de comestibles", "faro",
                "mirador", "dársena", "almacén", "motel", "posada", "lavandería", "peluquería", "bar", "restaurante",
                "cafetería", "banco", "oficina de correos", "tienda de antigüedades", "taller", "gimnasio", "spa", "sauna",
                "cementerio", "invernadero", "piscina", "río", "laguna", "lago", "estanque", "catarata", "volcán", "cueva",
                "acantilado", "isla desierta", "glaciar", "caverna", "jungla", "pantano", "estepa", "sabana", "valle",
                "meseta", "catarata", "pico", "fiordo", "desfiladero", "monte", "torre de vigilancia", "cuartel", "sala de conciertos",
                "teatro de ópera", "casa de cultura", "galería de arte", "salón de baile", "discoteca", "escalera", "ascensor",
                "puerta giratoria", "alfombra roja", "ventilador", "paraguas", "sombrilla", "linterna", "faro", "silla",
                "mesa", "cama", "escritorio", "armario", "estantería", "cómoda", "perchero", "espejo", "lámpara", "reloj",
                "piano", "guitarra", "batería", "trompeta", "flauta", "arpa", "violín", "tambores", "bongó", "maracas",
                "caja de música", "gramófono", "grabadora", "microscopio", "prismáticos", "telescopio", "parlantes", "robot",
                "bicicleta de ejercicio", "cinta de correr", "pesas", "máquina de remo", "reloj de arena", "botella de agua",
                "termo", "jarrón", "plato", "cuchara", "tenedor", "cuchillo", "olla", "sartén", "tetera", "colador",
                "cazuela", "taza", "vaso", "botella", "termo", "florero", "maceta", "regadera", "pala", "rastrillo",
                "carretilla", "manguera", "escalera de mano", "tijeras de podar", "azadón", "pico", "martillo", "destornillador",
                "taladro", "sierra", "lija", "alicate", "nivel de burbuja", "cinta métrica", "brújula", "mapa", "globo",
                "diario", "revista", "cómic", "cuaderno", "libro", "diccionario", "enciclopedia", "computadora", "impresora",
                "ratón", "teclado", "pantalla", "proyector", "micrófono", "audífonos", "celular", "teléfono", "altavoz",
                "televisor", "cámara", "lupa", "tarjeta de crédito", "cartera", "pasaporte", "mochila", "maleta", "bolso",
                "billetera", "estuche", "lapicero", "lápiz", "marcador", "plumón", "crayón", "borrador", "sacapuntas",
                "tijeras", "pegamento", "grapadora", "goma elástica", "clip", "cuadro", "poster", "escultura", "estatua",
                "fuente", "obelisco", "monumento", "torre", "columna", "arco", "puerta monumental", "mosaico", "fresco",
                "murales", "pintura", "galería", "artesanía", "telares", "alfombra", "tapiz", "florero", "cuenco", "joyero",
                "cajón", "bandeja", "cofre", "carroza", "bicicleta", "patines", "barco", "scooter", "moto", "tractor",
                "profesor", "médico", "enfermero", "ingeniero", "arquitecto", "chef", "pintor",
                "carpintero", "electricista", "plomero", "mecánico", "bombero", "policía", "piloto",
                "azafata", "abogado", "juez", "escritor", "periodista", "fotógrafo", "actor", "actriz",
                "músico", "cantante", "bailarín", "deportista", "entrenador", "veterinario", "científico",
                "astronauta", "programador", "estilista", "maestro", "niñera", "jardinero", "bibliotecario",
                "alcalde", "presidente", "rey", "reina", "príncipe", "princesa", "cazador", "pescador",
                "marinero", "navegante", "guardabosques", "arqueólogo", "historiador", "pintor de brocha gorda",
                "escultor", "peluquero", "barbero", "panadero", "pastelero", "camarero", "mesero",
                "repartidor", "chofer", "taxista", "actor de doblaje", "profesor de música", "director de cine",
                "productor", "investigador", "analista", "traductor", "intérprete", "consultor", "embajador",
                "secretario", "recepcionista", "asistente", "guardia de seguridad", "soldado", "general",
                "capitán", "cadete", "sargento", "juez de paz", "piloto de helicóptero", "terapeuta", "psicólogo",
                "psiquiatra", "dentista", "ortodoncista", "dermatólogo", "cardiólogo", "cirujano", "pediatra",
                "geriatra", "partera", "ayudante", "voluntario", "coordinador", "animador", "magistrado",
                "monje", "sacerdote", "pastor", "imán", "rabino", "monja", "corredor", "cazador de tormentas",
                "explorador", "instructor de yoga", "esquiador", "surfista", "paracaidista", "alpinista",
                "montañista", "zoologista", "entomólogo", "ecologista", "ambientalista", "activista", "candidato",
                "abogado de defensa", "fiscal", "artista gráfico", "pintor al óleo", "astrónomo", "matemático",
                "físico", "químico", "biólogo", "sociólogo", "antropólogo", "economista", "filósofo", "teólogo",
                "poeta", "crítico", "editor", "curador de museo", "conservador", "arqueólogo subacuático",
                "investigador privado", "detective", "policía forense", "comisario", "embalsamador", "entrenador personal",
                "nutricionista", "consultor financiero", "administrador de redes", "especialista en TI", "diseñador de interiores",
                "agente de viajes", "gerente de hotel", "conserje", "guardaparques", "agricultor", "ganadero", "apicultor",
                "viticultor", "floricultor", "horticultor", "paisajista", "empresario", "comerciante", "artesano", "ebanista",
                "herrero", "joyero", "relojería", "vidriero", "ceramista", "alfarero", "soplador de vidrio", "orfebre",
                "cerrajero", "empacador", "operador de maquinaria", "minero", "geólogo", "topógrafo", "meteorólogo",
                "físico nuclear", "robotista", "ingeniero químico", "ingeniero de software", "ingeniero civil", "ingeniero eléctrico",
                "ingeniero mecánico", "ingeniero de sonido", "ingeniero de telecomunicaciones", "ingeniero aeronáutico",
                "capitán de barco", "contratista", "ciclista", "motociclista", "automovilista", "velocista", "nadador",
                "triatleta", "gimnasta", "tenista", "futbolista", "basquetbolista", "voleibolista", "jugador de rugby",
                "jugador de hockey", "esgrimista", "luchador", "boxeador", "judoka", "karateka", "practicante de taekwondo",
                "espadachín", "tirador", "arquero", "jinete", "amazona", "entrenador de caballos", "adiestrador de perros",
                "titiritero", "mago", "ilusionista", "payaso", "ventrílocuo", "malabarista", "trapecista", "domador de leones",
                "cuidador de zoológico", "domador de serpientes", "falconero", "entrenador de aves", "cetrero", "cuidador de animales",
                "vendedor ambulante", "feriante", "artista callejero", "caricaturista", "bufón", "humorista", "comediante",
                "locutor", "anfitrión", "presentador", "moderador", "orador", "conferenciante", "maestro de ceremonias",
                "embajador cultural", "embajador de buena voluntad", "consejero", "psicoterapeuta", "coach de vida", "orientador",
                "tutor", "coordinador de eventos", "planificador de bodas", "diseñador de moda", "modelador 3D", "animador digital",
                "animador de videojuegos", "streamer", "youtuber", "blogger", "influencer", "redactor de contenido", "fotoperiodista",
                "corresponsal", "reportero de noticias", "editor de vídeo", "productor de cine", "diseñador de vestuario", "maquillador",
                "tatuador", "piercer", "guía turístico", "fotógrafo de paisajes", "viajero", "mochilero", "explorador urbano", "pescador deportivo",
                "niño", "adolescente", "adulto", "anciano", "vecino", "huésped", "visitante", "extranjero", "turista", "invitado",
                "mascota", "gato", "perro", "canario", "hamster", "conejo", "tortuga", "pez", "loro", "cobaya", "hurón",
                "lagarto", "serpiente", "iguana", "ratón", "rata", "erizo", "camaleón", "salamandra", "zorro", "lobo", "ciervo",
                "oso", "león", "tigre", "pantera", "guepardo", "jirafa", "elefante", "rinoceronte", "hipopótamo", "canguro",
                "koala", "panda", "delfín", "ballena", "foca", "pingüino", "pelícano", "flamenco", "águila", "halcón", "búho",
                "cigüeña", "pato", "ganso", "cisne", "cuervo", "paloma", "golondrina", "gorrión", "zorzal", "petirrojo", "picaflor",
                "colibrí", "mariposa", "abeja", "avispa", "hormiga", "catarina", "escarabajo", "saltamontes", "grillo", "mantis",
                "escorpión", "araña", "cangrejo", "langosta", "pulpo", "calamar", "tiburón", "raya", "medusa", "estrella de mar",
                "caballito de mar", "erizo de mar", "coral", "caracol", "babosa", "almeja", "ostra", "cocodrilo", "caimán", "tucán",
                "gorila", "orangután", "chimpancé", "mono", "babún", "lemur", "mapache", "zorrillo", "tejón", "comadreja"
            ],

            
            object: [
                "lápiz", "bolígrafo", "marcador", "pluma", "borrador", "sacapuntas", "regla", "compás",
                "escuadra", "cuaderno", "libro", "agenda", "carpeta", "portafolio", "mochila", "maleta",
                "estuche", "grapadora", "clip", "tijeras", "pegamento", "cinta adhesiva", "grapas",
                "calculadora", "computadora", "teclado", "ratón", "pantalla", "monitor", "impresora",
                "teléfono", "celular", "audífonos", "altavoz", "micrófono", "cámara", "televisor",
                "control remoto", "reloj", "reloj de pulsera", "reloj de pared", "reloj de arena", "brújula",
                "mapa", "globo terráqueo", "linterna", "batería", "cargador", "cable", "enchufe", "adaptador",
                "paraguas", "sombrilla", "lupa", "prismáticos", "telescopio", "microscopio", "jarrón",
                "florero", "maceta", "planta", "regadera", "manguera", "pala", "rastrillo", "carretilla",
                "escalera", "martillo", "destornillador", "taladro", "sierra", "alicate", "llave inglesa",
                "cinta métrica", "nivel de burbuja", "serrucho", "lija", "cepillo", "brocha", "pincel",
                "paleta de pintor", "rodillo", "esmalte", "cubo", "esponja", "jabón", "champú", "toalla",
                "cepillo de dientes", "pasta de dientes", "hilo dental", "peine", "cepillo de pelo",
                "secador de pelo", "plancha", "pinza para el pelo", "espejo", "rasuradora", "maquinilla",
                "desodorante", "perfume", "loción", "crema", "sombrero", "gorro", "bufanda", "guantes",
                "botas", "zapatillas", "zapatos", "sandalias", "chanclas", "camisa", "blusa", "chaqueta",
                "abrigo", "chaleco", "pantalones", "falda", "vestido", "corbata", "cinturón", "calcetines",
                "medias", "pijama", "bata", "traje", "uniforme", "moño", "lazo", "gafas", "lentes de sol",
                "máscara", "antifaz", "casco", "collar", "pulsera", "anillo", "pendientes", "aretes",
                "reloj de bolsillo", "broche", "pasador", "gemelos", "alhajero", "cofre", "joyero", "cajón",
                "cómoda", "armario", "mesa", "silla", "taburete", "sofá", "sillón", "mecedora", "cama",
                "colchón", "almohada", "funda", "manta", "sábana", "edredón", "cobija", "cuna", "lámpara",
                "lámpara de pie", "candelabro", "pantalla de lámpara", "ventilador", "radiador", "calefactor",
                "aire acondicionado", "termostato", "refrigerador", "congelador", "microondas", "horno",
                "tostadora", "batidora", "licuadora", "cafetera", "tetera", "olla", "cazuela", "sartén",
                "cuchara", "tenedor", "cuchillo", "espátula", "colador", "rallador", "tabla de cortar",
                "abrelatas", "sacacorchos", "cucharón", "cuchillo de pan", "cuchillo de chef", "pinzas",
                "espumadera", "copa", "vaso", "taza", "plato", "bandeja", "fuente", "tazón", "juguera",
                "termo", "botella", "botella de agua", "tapón", "lata", "tarro", "caja", "bote", "contenedor",
                "basurero", "papelera", "escoba", "recogedor", "mopa", "cubeta", "trapeador", "aspiradora",
                "robot aspirador", "lavadora", "secadora", "plancha de ropa", "tabla de planchar", "perchero",
                "gancho", "colgador", "porta sombrillas", "baúl", "maletín", "carrito de compras", "bandeja de entrada",
                "archivador", "puerta", "ventana", "persiana", "cortina", "cerradura", "llave", "manilla", "picaporte",
                "interruptor", "enchufe múltiple", "luz nocturna", "bombilla", "foco", "farol", "campana", "alarma",
                "silbato", "timbre", "campanilla", "pito", "bocina", "megáfono", "altavoz portátil", "bocadillo inflable",
                "carrete de hilo", "agujas", "tijeras de costura", "alfiletero", "dedal", "hilo", "madeja", "tela",
                "retazo", "parche", "bolso", "mochila", "cartuchera", "monedero", "billetera", "funda de móvil",
                "bandeja de hielo", "molde para hornear", "bolsa de plástico", "papel de regalo", "papel aluminio",
                "película transparente", "cortapapeles", "sello", "marcador permanente", "tarjeta", "postal", "sobre",
                "carta", "invitación", "pegatina", "tarjeta de cumpleaños", "notebook", "tableta", "consola de videojuegos",
                "mando", "joystick", "tarjeta de memoria", "disco duro", "usb", "lápiz óptico", "cámara web", "trípode",
                "foco de estudio", "microscopio", "proyector", "pantalla de proyección", "filtro de luz", "pizarra blanca",
                "marcadores de pizarra", "borrador de pizarra", "estante", "repisa", "mueble de televisión", "aparador",
                "vitrina", "armario de cocina", "banco de herramientas", "cajonera", "espejo de pie", "toallero", "perchero de pie"
            ]
            ,

            action: [
                "correr", "saltar", "nadar", "bailar", "caminar", "trepar", "luchar", "volar",
                "esquiar", "patinar", "andar", "gatear", "lanzar", "patear", "golpear", "empujar",
                "tirar", "levantar", "agacharse", "saltar la cuerda", "rodar", "deslizarse", "rebotar",
                "atrapar", "perseguir", "huir", "escalar", "sumergirse", "navegar", "remar", "saltar en paracaídas",
                "bucear", "esquivar", "boxear", "luchar", "golpear con el codo", "patinar sobre hielo", "pedalear",
                "subir escaleras", "bajar escaleras", "patinar en línea", "hacer flexiones", "hacer sentadillas",
                "saltar obstáculos", "remar", "tirarse en tirolesa", "acampar", "escribir", "leer", "dibujar",
                "pintar", "esculpir", "tejer", "cortar", "pegar", "coser", "bordar", "clavar", "atornillar",
                "limpiar", "barrer", "fregar", "trapeador", "sacudir", "ordenar", "lavar", "planchar", "doblar ropa",
                "regar", "podar", "jardinear", "cocinar", "freír", "asar", "hornear", "rebanar", "pelar", "revolver",
                "batir", "mezclar", "decorar", "degustar", "sazonar", "marinar", "hervir", "enfriar", "congelar",
                "descongelar", "tostar", "preparar", "comer", "beber", "masticar", "tragar", "sorber", "saborear",
                "dormir", "soñar", "roncar", "despertar", "levantarse", "sentarse", "acostarse", "saltar de la cama",
                "dormitar", "descansar", "relajarse", "meditar", "respirar", "concentrarse", "pensar", "analizar",
                "recordar", "olvidar", "imaginar", "crear", "inventar", "planear", "organizar", "calcular", "sumar",
                "restar", "multiplicar", "dividir", "escribir a máquina", "dictar", "programar", "dibujar planos",
                "caligrafiar", "tomar notas", "leer en voz alta", "recitar", "narrar", "cantar", "tocar un instrumento",
                "afinar", "silbar", "tararear", "improvisar", "actuar", "ensayar", "aplaudir", "festejar", "brindar",
                "celebrar", "bailar salsa", "bailar tango", "zambullirse", "tomar el sol", "jugar", "competir",
                "participar", "ganar", "perder", "empatizar", "conversar", "charlar", "escuchar", "preguntar", "responder",
                "enseñar", "aprender", "estudiar", "explicar", "traducir", "interpretar", "enseñar a leer", "educar",
                "viajar", "explorar", "descubrir", "navegar en barco", "volar en avión", "hacer maletas", "desempacar",
                "acampar", "hacer senderismo", "montar a caballo", "surfear", "navegar en kayak", "pescar", "cazar",
                "fotografiar", "filmar", "editar", "subir contenido", "transmitir", "descargar", "subir archivos", "escanear",
                "imprimir", "fotocopiar", "organizar reuniones", "coordinar", "supervisar", "liderar", "delegar",
                "inspirar", "motivar", "convencer", "negociar", "discutir", "mediar", "conciliar", "firmar",
                "sellar", "aprobar", "rechazar", "aceptar", "proponer", "presentar", "preparar un informe", "disertar",
                "conferenciar", "comentar", "publicar", "redactar", "revisar", "corregir", "gritar", "susurrar",
                "reír", "llorar", "gritar de alegría", "aplaudir con entusiasmo", "susurrar un secreto", "aclamar",
                "exclamar", "quejarse", "refunfuñar", "protestar", "apaciguar", "tranquilizar", "persuadir", "asustar",
                "sorprender", "bromear", "contar chistes", "hacer reír", "hacer llorar", "emocionar", "aburrir",
                "desanimar", "despedir", "saludar", "despedirse", "abrazar", "dar la mano", "chocar los cinco", "palmear",
                "empujar suavemente", "acariciar", "besar", "dar un beso en la mejilla", "apretar", "pellizcar", "acariciar el cabello",
                "hacer cosquillas", "asustarse", "calmarse", "relajarse", "estirarse", "bocear", "desperezarse", "pestañear",
                "guiñar un ojo", "sonreír", "hacer pucheros", "hacer muecas", "poner caras", "fruncir el ceño", "levantar una ceja",
                "gesticular", "asentir", "negar con la cabeza", "cruzar los brazos", "encogerse de hombros", "dar la vuelta",
                "girar", "inclinarse", "ponerse de pie", "sentarse de golpe", "arrojar", "dar una patada", "saltar sobre un pie",
                "dar volteretas", "hacer el pino", "saltar la cuerda", "hacer piruetas", "saltar a la comba", "balancearse",
                "balancear los brazos", "hacer ejercicio", "entrenar", "hacer yoga", "hacer pilates", "hacer tai chi", "boxear",
                "practicar artes marciales", "jugar al fútbol", "jugar al tenis", "jugar al baloncesto", "jugar al voleibol", "rematar",
                "golpear con el puño", "dar un codazo", "correr una maratón", "sprintar", "trotar", "hacer bicicleta", "escalar rocas"
            ]
            ,

            difficulty: [
                "destino", "utopía", "misterio", "suspenso", "soledad", "éxtasis", "arrogancia", "miedo",
                "duda", "esperanza", "traición", "serenidad", "pasión", "introspección", "inteligencia", 
                "curiosidad", "pérdida", "ambición", "compasión", "orgullo", "libertad", "paz", "guerra", 
                "confusión", "recuerdo", "melancolía", "nostalgia", "perseverancia", "admiración", "cautela", 
                "resiliencia", "equilibrio", "justicia", "venganza", "inocencia", "sabiduría", "tentación", 
                "claridad", "oscuridad", "infinito", "progreso", "retroceso", "armonía", "desesperanza", 
                "decepción", "redención", "gratitud", "simpatía", "tolerancia", "ignorancia", "desdicha", 
                "euforia", "desolación", "epifanía", "conformidad", "desafío", "sacrificio", "creatividad", 
                "abundancia", "vacío", "percepción", "intuición", "conciencia", "subconsciente", "paradoja", 
                "revelación", "apariencia", "ideal", "contradicción", "felicidad", "tristeza", "misericordia", 
                "tentación", "paradigma", "caos", "orden", "reciprocidad", "dualidad", "moralidad", "ética", 
                "virtud", "pecado", "culpa", "remordimiento", "identidad", "transformación", "purificación", 
                "esperanza", "desafío", "superación", "soledad", "compañerismo", "sueño", "realidad", "espejismo", 
                "verdad", "mentira", "inspiración", "altruismo", "escepticismo", "ambivalencia", "individualismo", 
                "colectivismo", "heroísmo", "villanía", "impulso", "razón", "emoción", "empatía", "desprecio", 
                "anhelo", "apatía", "apatía", "fatiga", "determinación", "constancia", "innovación", "tradición", 
                "valor", "timidez", "imaginación", "visión", "ambigüedad", "autoridad", "rebelión", "conformismo", 
                "vitalidad", "aletargamiento", "caída", "auge", "paradoja", "inquietud", "serenidad", "desenlace", 
                "inicio", "culminación", "simbiosis", "parasito", "complicidad", "discordia", "afinidad", "antipatía", 
                "irresponsabilidad", "madurez", "inmadurez", "transcendencia", "inmanencia", "adversidad", "plenitud", 
                "vacuidad", "escepticismo", "convicción", "dogma", "relatividad", "absoluto", "desafío", "aplomo", 
                "fuerza", "vulnerabilidad", "ocultismo", "transparencia", "mística", "terrenal", "espiritual", "pragmático", 
                "utópico", "distopía", "sátira", "ironía", "sarcasmo", "optimismo", "pesimismo", "neutralidad", "compromiso", 
                "alienación", "cautela", "impetuosidad", "ansiedad", "calma", "resplandor", "oscuridad", "transición", 
                "expectativa", "realización", "fracaso", "triunfo", "fe", "distracción", "atención", "concentración", 
                "abstracción", "simbolismo", "ritual", "costumbre", "instinto", "impulso", "delirio", "cordura", "locura", 
                "sentido", "absurdo", "sofisticación", "sencillez", "enigma", "revelación", "impresión", "espectáculo", 
                "cotidianidad", "extrañeza", "normalidad", "excepción", "riesgo", "seguridad", "fragilidad", "fortaleza", 
                "perfección", "imperfección", "trivialidad", "profundidad", "determinación", "hesitación", "resolución", 
                "conflicto", "alianza", "cooperación", "competencia", "alianza", "estrategia", "táctica", "impulsividad", 
                "calculación", "fuerza", "destreza", "habilidad", "torpeza", "entusiasmo", "desgano", "admiración", 
                "resentimiento", "piedad", "indiferencia", "preocupación", "alivio", "cautela", "temeridad", "certeza", 
                "sospecha", "comprensión", "desconcierto", "facilidad", "complicación", "holgura", "tensión", "disponibilidad", 
                "ausencia", "presencia", "alegría", "tristeza", "satisfacción", "deseo", "repulsión", "entrega", "reserva", 
                "recelo", "desprendimiento", "cariño", "odio", "admiración", "conformidad", "rebeldía", "vanguardia", "tradición", 
                "modernidad", "antigüedad", "futuro", "pasado", "presente", "simetría", "asimetría", "desequilibrio", "balance", 
                "inevitabilidad", "accidente", "intencionalidad", "azar", "destino", "libre albedrío", "juicio", "prejuicio", 
                "percepción", "distorsión", "realismo", "idealismo", "materialismo", "espiritualismo", "proporción", "desorden", 
                "resolución", "ambigüedad", "facilitar", "entorpecer", "acercamiento", "alejamiento", "frustración", "cumplimiento", 
                "asombro", "monotonía", "fascinación", "desprecio", "ansia", "repugnancia", "satisfacción", "disgusto", "fervor", 
                "apatía", "ambición", "temor", "valentía", "temeridad", "prudencia", "irresponsabilidad", "conciencia", "autonomía", 
                "dependencia", "liberación", "reclusión", "impulso", "reflexión", "elocuencia", "tartamudeo", "fluidez", "bloqueo", 
                "originalidad", "cliché", "evolución", "repetición", "renovación", "decadencia", "ascenso", "caída", "flujo", 
                "estancamiento", "dinamismo", "inmovilidad", "permanencia", "transitoriedad", "inmediatez", "posteridad"
            ],        
            movies:
            [
                "titanic","la guerra de las galaxias","harry potter","friends","juego de tronos","el rey león","breaking bad","avatar",
                "vengadores","parque jurásico","los simpson","stranger things","el padrino","matrix","the office","el caballero oscuro",
                "frozen: el reino del hielo","the big bang theory","el señor de los anillos","marvel","the mandaloriano","bob esponja",
                "superman","wonder woman","piratas del caribe","the crown","the witcher","origen","seinfeld","batman","sherlock","anatomía de grey",
                "toy story","los soprano","demogorgon","black panther","la casa de papel","the walking dead","peaky blinders","iron man","capitán américa",
                "thor","loki","deadpool","shrek","minions","james bond","rocky","indiana jones","dexter","arrow","flash","joker","han solo","rey",
                "luke skywalker","darth vader","princesa leia","spiderman","venom","hulk","viuda negra","doctor extraño","guardianes de la galaxia",
                "lobezno","x-men","westworld","mad men","house of cards","the umbrella academy","narcos","breaking bad (walter white)","vikingos",
                "eltablerodechuleta","lost","cómo conocí a vuestra madre","hannah montana","padre de familia","futurama","rick and morty","big mouth",
                "bojack horseman","the boys","lucifer","black mirror","el cuento de la criada","west side story","pulp fiction","forrest gump",
                "cadena perpetua","buenos muchachos","la lista de schindler","gladiator","salvar al soldado ryan","la milla verde","infiltrados",
                "club de la lucha","seven","el truco final","memento","dunkerque","interestelar","gravedad","casablanca","cantando bajo la lluvia",
                "el mago de oz","ciudadano kane","ventana indiscreta","psicosis","tiburón","et el extraterrestre","coco","del revés","moana","mulán",
                "aladdín","la bella y la bestia","la sirenita","la bella durmiente","blancanieves","pocahontas","buscando a nemo","buscando a dory",
                "monstruos s.a.","ratatouille","up","cars","valiente","wall‑e","lilo y stitch","tarzán","el libro de la selva","frozen 2","zootrópolis",
                "megamiente","los increíbles","ant‑man","capitana marvel","shang‑chi","eternals","spider‑man: lejos de casa","spider‑man: sin camino a casa",
                "mission: impossible","mision imposible","fast and furious","a todo gas","la jungla de cristal","duro de matar","arma letal","depredador",
                "terminator","terminator 2","robocop","matrix revolutions","john wick","john wick 2","john wick 3","el efecto mariposa","el club de los poetas muertos",
                "la red social","her","wall street","el lobo de wall street","social network","la gran estafa americana","inside man","heat","el precio del poder","scarface",
                "granujas a todo ritmo","el gran lebowski","snatch: cerdos y diamantes","lock, stock and two smoking barrels","trainspotting","regreso al futuro",
                "regreso al futuro II","regreso al futuro III","muerte en el nilo","asesinato en el orient express","entre navajas y secretos","la isla siniestra",
                "shutter island","el sexto sentido","sexto sentido","el jardín secreto","los puentes de madison","el patriota","forrest gump","el indomable will hunting",
                "good will hunting","american pie","diario de una pasión","the notebook","diario de una pasion","fantasma","ghost","dirty dancing","grease","brillantina",
                "flashdance","footloose","chicago","mamma mia","los miserables","el rey pescador","el último mohicano","la princesa prometida","princesa prometida",
                "amor y monstruos","la forma del agua","shape of water","la lista de schindler","salvando al soldado ryan","soldado ryan","salvando","los odiosos ocho",
                "hateful eight","django desencadenado","bastardos sin gloria","inglourious basterds","pulp fiction","jackie brown","kill bill","rescatando al soldado ryan",
                "muchachada nui","monty python","la vida de brian","holy grail","peregrino palpitante","beloved","lo que el viento se llevó","gone with the wind","el gran dictador",
                "the great dictator","temibles tiburones","jaws","tiburón","corea","korean drama","drama coreano","casa papel","naruto","one piece","dragon ball",
                "dragon ball z","attack on titan","shingeki no kyojin","fullmetal alchemist","tokyo ghoul","death note","bleach","sailor moon","my hero academia",
                "bnha","fairy tail","hunter x hunter","cowboy bebop","samurai champloo","code geass","neon genesis evangelion","evangelion","steins;gate","no game no life",
                "overlord","konosuba","kaguya-sama","kimi no na wa","your name","el viaje de chihiro","chihiro","princesa mononoke","mononoke","totoro","tonari no totoro",
                "la princesa mononoke","arrebatadora","kiki entrega a domicilio","ponyo","ponyo","el castillo ambulante","howl's moving castle","el viento se levanta",
                "grave of the fireflies","la tumba de las luciérnagas","spirited away","whisper of the heart","calcifer","ni no kuni","ni no kuni la ira de la bruja blanca",
                "trinity blood","tabernero loca","seven deadly sins","meliodas","full metal panic","gantz","parasyte","tokyo revengers","pink flamingos","el padrino II",
                "el padrino III","the godfather part II","godfather II","godfather III","the godfather part III","scarface","the departed","infiltrados",
                "shang chi y la leyenda de los diez anillos","black widow","captain america: civil war","civil war","avengers: age of ultron","age of ultron",
                "vengadores: era de ultrón","vengadores infinita","infinity war","avengers: infinity war","guardians of the galaxy vol. 3","multiverse of madness",
                "doctor strange en el multiverso de la locura","spider‑man: un nuevo universo","into the spider‑verse","spider‑verse","spiderverse","ocho apellidos vascos"
            ]               
        };